import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { translationDictionary } from './dictionary_part1.js';
import { dictionaryPart2 } from './dictionary_part2.js';
import { dictionaryPart3 } from './dictionary_part3.js';
import { dictionaryPart4 } from './dictionary_part4.js';
import { dictionaryPart5 } from './dictionary_part5.js';
import { dictionaryPart6 } from './dictionary_part6.js';
import { dictionaryPart7 } from './dictionary_part7.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MASTER_DICT = {
  ...translationDictionary,
  ...dictionaryPart2,
  ...dictionaryPart3,
  ...dictionaryPart4,
  ...dictionaryPart5,
  ...dictionaryPart6,
  ...dictionaryPart7
};

// Additional phrase translations
const PHRASES = {
  "Sun Rise In The East": "شروق الشمس في الشرق",
  "I said it to Stepan's face.": "قلت ذلك لستيبان في وجهه مباشرة.",
  "I... I feel like I should remember some special moment to tell you about.": "أنا... أشعر وكأنني ينبغي أن أتذكر لحظة مميزة لأحدثك عنها.",
  "Trapped here, like I am.": "عالق هنا، مثلي تماماً.",
  "find recording equipment.": "اعثر على معدات التسجيل.",
  "\"Dig\"": "\"احفر\"",
  "(c)Strata industries 1976-1982": "(حقوق النشر) صناعات ستراتا 1976-1982",
  "*** ALERT ***": "*** تنبيه خطر ***",
  "*END OF RECORDING*": "*نهاية التسجيل*",
  "*breathing struggles in the background*": "*أنفاس متقطعة ومكافحة في الخلفية*",
  "*coughs in background*": "*سعال في الخلفية*",
  "*static and rustling*": "*تشويش وخشخشة*",
  "... connection lost due to poor reception.": "... انقطع الاتصال بسبب ضعف الإشارة.",
  "... strange symptoms.": "... أعراض غريبة وغير مفهومة.",
  "....Me? Talk?": "....أنا؟ أتكلم؟",
  "1 NEW ORDER": "1 أمر جديد",
  "1. Record": "1. تسجيل",
  "2. Process data": "2. معالجة البيانات",
  "3. Get coordinates": "3. استخراج الإحداثيات",
  "31 LOG ENTRIES FOUND": "تم العثور على 31 سجلاً",
  "3333333333333<cf>3333333333333<cf>FATHER<cf>SAVIOUR<cf>NOT ENOUGH": "3333333333333<cf>3333333333333<cf>أبي<cf>المخلّص<cf>ليس كافياً",
  "A Sun That Never Sets - Petro Kaminskyi": "شمس لا تغرب أبداً - بيترو كامينسكي",
  "A common tool. Rust and blood mix along the shaft.": "أداة اعتيادية. يمتزج الصدأ بالدم على طول عمودها.",
  "A compact model. twin spools visible through the scratched plastic shell.": "طراز مدمج. تظهر البكرتان من خلال الغلاف البلاستيكي المخدوش.",
  "A crazy way to make a path between our vessels for sure, but we'll take it.": "طريقة مجنونة بكل تأكيد لشق طريق بين سفننا، لكننا سنمضي بها.",
  "A fan component for a bigger machine.": "قطعة مروحة لآلة أكبر.",
  "A flawed, mass-produced relic of a simpler time. Used to interpret navigational data.": "أثر مشوب بالعيوب من زمن أبسط. يُستخدم لقراءة البيانات الملاحية.",
  "A heavy flashlight, its metal casing cold to the touch.": "مصباح يدوي ثقيل، غلافه المعدني بارد الملمس.",
  "A neural cassette has been issued to a registered name.": "تم إصدار كاسيت عصبي باسم مسجل.",
  "A simple key": "مفتاح بسيط",
  "A source of false security, yes. But it will guide your path all the same.": "مصدر أمان زائف، نعم. لكنه سيرشدك في دربك على أية حال.",
  "A standard issue Strata seismic data cassette.": "كاسيت بيانات زلزالية قياسي صادر عن ستراتا.",
  "A steel wrench existing on borrowed time.": "مفتاح ربط فولاذي يعيش على وقت مستقطع.",
  "A steel wrench still serving faithfully long past its expiration date.": "مفتاح ربط فولاذي يخدم بوفاء رغم تجاوزه الأجل.",
  "About Yosep.": "بشأن يوسف.",
  "About the state of the mission.": "بشأن حالة المهمة.",
  "About whatever monstrosity has made its way into the vessel with you.": "بشأن ذلك الوحش الذي تسلل إلى السفينة معكم.",
  "Adjust the RPM with the throttle by terrain density": "اضبط دورات الخانق (RPM) حسب كثافة التضاريس",
  "Adjust the gamma until the left rabbit is barely visible.": "اضبط غاما حتى يصبح الأرنب الأيسر مرئياً بالكاد.",
  "Administrator access confirmed.": "تم تأكيد وصول المسؤول الإداري.",
  "Align retinal mark with chart.": "طابق علامة شبكية العين مع المخطط.",
  "All I can do now is tell you how sorry I am.": "كل ما يسعني فعله الآن هو أن أقول لك كم أنا آسف.",
  "All that remains of your son is inscribed on this cassette. It is the reason why you are here.": "كل ما تبقى من ابنك محفور على هذا الكاسيت. إنه السبب الذي أتى بك إلى هنا.",
  "All these things I want to teach him. All these things I want him to experience.": "كل هذه الأشياء أردت تعليمه إياها، وكل هذه التجارب أردت أن يخوضها.",
  "All we know is that it's calling from deep below the earth": "كل ما نعلمه هو أنها تنادي من أعماق سحيقة تحت الأرض",
  "All you have is that bullshit cassette full of fake memories.": "ليس معك سوى ذلك الكاسيت التافه المليء بذكريات زائفة.",
  "Almost.": "تقريباً.",
  "And Hrytsenko is not truly needed to operate the vessel, is he?": "وهريتسينكو ليس ضرورياً لتشغيل السفينة، أليس كذلك؟",
  "And I get the feeling they don't want us to leave.": "وينتابني شعور بأنهم لا يريدوننا أن نغادر.",
  "And I want you to know I will always be proud of you.": "وأريدك أن تعلم أنني سأظل دائماً فخوراً بك.",
  "And above all, you knew what risks those selections would bring.": "وفوق كل شيء، كنت تعلم ما هي المخاطر التي ستترتب على تلك الاختيارات.",
  "And did he? Did he get a recording of the Signal?": "وهل فعل؟ هل حصل على تسجيل للإشارة؟",
  "And even though their saviours sacrifice everything.": "ورغم أن مخلصيهم يضحون بكل شيء.",
  "And in the end, perhaps we can both find redemption.": "وفي الختام، لعلينا معاً نجد الخلاص.",
  "And now we are here, and so much damage has already been done.": "وها نحن هنا، وقد وقع الكثير من الدمار بالفعل.",
  "And now you've hit a dead end.": "والآن وصلت إلى طريق مسدود.",
  "And perhaps you can help me too.": "وربما يسعك مساعدتي أيضاً.",
  "And that explosion just now was your doing, yeah?": "وهذا الانفجار قبل قليل كان من فعلك، أليس كذلك؟",
  "And the engineer, Bohdan Pluzhnik, tried to stop him?": "والمهندس، بوهدان بلوجنيك، حاول إيقافه؟",
  "And, no, Stepan. It won't be you.": "وكلا، يا ستيبان. لن تكون أنت.",
  "Any contact with the Signal seems to result in...": "أي احتكاك بالإشارة يبدو أنه يؤدي إلى...",
  "Apartment Key": "مفتاح الشقة",
  "Are you certain?": "هل أنت متأكد؟",
  "As for me, I fear I'll never be able to let go.": "أما عني، فأخشى أنني لن أستطيع التجاوز أبداً.",
  "As long as even a single crew member remains alive the public won't accept you giving up.": "ما دام هناك عضو واحد من الطاقم حياً، فلن يتقبل الجمهور استسلامك.",
  "As long as you are in here I can hold it off": "طالما أنك هنا بالداخل يمكنني صدّه ومقاومته",
  "As we get closer.": "كلما اقتربنا أكثر.",
  "Attention. Engine failure detected. Immediate repair required.": "انتباه. تم رصد عطل في المحرك. يلزم إصلاح فوري.",
  "Attention. No valid waypoint. Acquire updated coordinates from the laboratory.": "انتباه. لا توجد نقطة مسار صالحة. احصل على إحداثيات محدثة من المختبر.",
  "Attention. Perilous terrain ahead. Deploy torpedo from the engine hall to resume drilling.": "انتباه. تضاريس شديدة الخطورة أمامك. أطلق طوربيداً من قاعة المحركات لمتابعة الحفر.",
  "Attention. Power Failure detected. Restore power manually via the main fuse box.": "انتباه. تم رصد انقطاع الكهرباء. استعد الطاقة يدوياً عبر صندوق المصاهر الرئيسي.",
  "Attention. Vessel engine is once again operational. New course correction is required.": "انتباه. عاد محرك السفينة للعمل. يلزم إجراء تصحيح جديد للمسار.",
  "Attention. Vessel is off course. Course correction required.": "انتباه. السفينة خارج المسار. يلزم تصحيح المسار فوراً.",
  "BE CAREFUL": "كن حذراً",
  "BE CAREFUL<cf><cf><cf>IT IS WAKING UP": "كن حذراً<cf><cf><cf>إنه يستيقظ الآن",
  "BRING THE CASSETTE TO ME": "أحضر الكاسيت إليّ",
  "BULLSEYE": "إصابة دقيقة في الصميم",
  "Be careful.": "توخَّ الحذر.",
  "Before we proceed, please remember:": "قبل أن نتابع، يُرجى التذكّر:",
  "Between life and death.": "بين الحياة والموت.",
  "Bicycle": "دراجة هوائية",
  "Birthday.": "عيد ميلاد.",
  "Board the other vessel": "اصعد على متن السفينة الأخرى",
  "Body": "الجسد",
  "Bohdan here, please answer.": "بوهدان هنا، أجبني أرجوك.",
  "Boooo!": "بوووو!",
  "Bottom View": "منظر سفلي",
  "Break through all that which still keeps him from you.": "اخترق كل ما لا يزال يحجبه عنك.",
  "Break through death.": "اخترق الموت.",
  "Break through the past.": "اخترق قيود الماضي.",
  "Breathe out.": "أخرج زفيرك.",
  "Bring him to the TV.": "خذه إلى التلفاز.",
  "Bring us together.": "اجمع شملنا معاً.",
  "Build": "البناء",
  "But I am bound to this place - and my reach is frustatingly limited.": "لكنني مقيد بهذا المكان - ومدى قدرتي محدود بشكل محبط.",
  "But I can't.": "لكنني عاجز عن ذلك.",
  "But I do.": "لكنني أشعر بذلك.",
  "But I have no such limits.": "لكن ليس لدي مثل هذه القيود.",
  "But I refuse to let you suffer my fate.": "لكنني أرفض أن تعاني من نفس مصيري.",
  "But I still can't reach him.": "لكنني ما زلت غير قادر على الوصول إليه.",
  "But Strata never paid for their mistakes.": "لكن ستراتا لم تدفع ثمن أخطائها قط.",
  "But a boy should not have to live his life trapped in a dream.": "لكن لا ينبغي لصبي أن يحيا حبيساً في حلم.",
  "But be careful, son.": "لكن احذر يا بني.",
  "But don't worry. I won't keep you.": "لكن لا تقلق، لن أعطلك.",
  "But don't worry. You will be the first to watch it.": "لكن لا تقلق. ستكون أول من يشاهده.",
  "But first, come meet me in my dorm.": "لكن أولاً، تعال وقابلني في مهجعي.",
  "But for you this is not the end.": "لكن بالنسبة لك، ليست هذه هي النهاية.",
  "But in my dorm there's-": "لكن في مهجعي هناك-",
  "But it doesn't have to be set in stone.": "لكن الأمر ليس محتوماً ولا منقوشاً في الحجر.",
  "But it's been a disturbingly long time since we receieved any data at all from his lab.": "لكن مضى وقت طويل ومقلق منذ أن استلمنا أي بيانات على الإطلاق من مختبره.",
  "But sometimes you just have to accept reality.": "لكن في بعض الأحيان عليك فقط تقبل الواقع.",
  "But that doesn't change anything, Stepan.": "لكن ذلك لا يغير شيئاً يا ستيبان.",
  "But there are no such limitation upon you.": "لكن لا توجد مثل هذه القيود عليك أنت.",
  "But they also knew the risks.": "لكنهم كانوا يعلمون المخاطر أيضاً.",
  "But they won’t write my name in the report": "لكنهم لن يكتبوا اسمي في التقرير",
  "But we HAVE to keep digging.": "لكن يتوجب علينا مواصلة الحفر.",
  "But you are right.": "لكنك على حق.",
  "But you can't run from the past forever": "لكنك لا تستطيع الهروب من الماضي للأبد",
  "But you have already known me for a long time": "لكنك تعرفني بالفعل منذ زمن بعيد",
  "But you need to make a new recording, even if Hrytsenko, is unable to do so himself.": "لكن عليك إجراء تسجيل جديد، حتى وإن كان هريتسينكو عاجزاً عن ذلك بنفسه.",
  "But you need to remember why you have to keep digging.": "لكن عليك أن تتذكر السبب الذي يجعلك تواصل الحفر.",
  "But you still refused to believe death would be the end.": "لكنك واصلت رفض تصديق أن الموت هو النهاية.",
  "Call Taras.": "اتصل بتاراس.",
  "Can you please turn on the radio?": "هل يمكنك تشغيل المذياع أرجوك؟",
  "Can you read me?…Stepan?": "هل تسمعني؟... ستيبان؟",
  "Careful.": "كن حذراً.",
  "Careful. <cf><cf>It is here.": "حذارِ. <cf><cf>إنه هنا.",
  "Cassette type is: TARGETING COORDINATES<cf><cf>Compatible with: COCKPIT TERMINAL": "نوع الكاسيت: إحداثيات الاستهداف<cf><cf>متوافق مع: شاشة قمرة القيادة",
  "Cheap opium to numb the pain. Once a lifeline, now redundant.": "أفيون رخيص لتسكين الألم. كان شريان حياة يوماً، والآن أصبح بلا فائدة.",
  "Checkpoint reached": "تم الوصول لنقطة الحفظ",
  "Clear manual piloting with 1 minute to spare.": "أنهِ التوجيه اليدوي قبل دقيقة من نفاذ الوقت.",
  "Close your eyes. Breathe through the numbers.<cf><cf><cf>83:17:02<cf><cf><cf>Like a verse out of the bible.": "أغمض عينيك. تنفس عبر الأرقام.<cf><cf><cf>83:17:02<cf><cf><cf>كالآية المقتبسة من الإنجيل.",
  "Couldn't Adamenko have used the gun himself?": "ألم يكن بمقدور أدامينكو استخدام المسدس بنفسه؟",
  "Cut Extraction cables?<cf><cf>FOR III<cf><cf>She wants us to DIG": "قطع كابلات الإخلاء؟<cf><cf>من أجل III<cf><cf>إنها تريدنا أن نحفر",
  "Cutting edge neurological data storage. Repurposed by Strata to contain readings of something of equal complexity.": "وحدة تخزين بيانات عصبية متطورة للغاية. أعادت ستراتا توظيفها لاحتواء قراءات لشيء بنفس القدر من التعقيد.",
  "DANGER<cf>CONFINED SPACE": "خطر<cf>مكان ضيق ومحصور",
  "DATA ENCRYPTED": "البيانات مشفرة",
  "DATA TYPE.............. KEY": "نوع البيانات.............. مفتاح وصول",
  "DATA TYPE.............. SEISMIC DATA": "نوع البيانات.............. بيانات زلزالية",
  "DETONATE WITH CLACKER": "فجّر باستخدام المفجر اليدوي",
  "DETONATION COMPLETE": "اكتمل التفجير بنجاح",
  "DETONATION READY": "جاهز للتفجير",
  "DIAGNOSTICS REPORT": "تقرير الفحص والتشخيص",
  "DISTANCE REMAINING": "المسافة المتبقية",
  "DO NOT GO UP": "لا تصعد للأعلى",
  "DO NOT REMOVE CASSETTE": "لا تنزع الكاسيت",
  "DON'T LINGER": "لا تتباطأ ولا تمكث هنا",
  "DOOR 311": "الباب 311",
  "DORM 02, GEOLOGY LAB<cf><cf>INSERT INTO A DOOR PANEL": "المهجع 02، مختبر الجيولوجيا<cf><cf>أدخله في لوحة الباب",
  "DORM 03, TORPEDO ROOM<cf><cf>INSERT INTO A DOOR PANEL": "المهجع 03، غرفة الطوربيد<cf><cf>أدخله في لوحة الباب",
  "DORM 04, DECK FLOOR<cf><cf>INSERT INTO A DOOR PANEL": "المهجع 04، طابق السطح<cf><cf>أدخله في لوحة الباب",
  "Dad, I miss you": "أبي، أنا أفتقدك",
  "Dad, where are you?": "أبي، أين أنت؟",
  "Data Recorded": "تم تسجيل البيانات",
  "Data must be decrypted<cf>in a seismic terminal": "يجب فك تشفير البيانات<cf>في شاشة الرصد الزلزالي",
  "Days until salvation:": "الأيام المتبقية حتى الخلاص:",
  "Did I not explicitly ask you NOT to do anything stupid?": "ألم أطلب منك صراحة ألا تفعل أي حماقة؟",
  "Dig": "احفر",
  "Dig.": "احفر.",
  "Digging.": "حفر.",
  "Distance to Safe Zone:": "المسافة إلى المنطقة الآمنة:",
  "Do NOTHING.": "لا تفعل أي شيء.",
  "Do not leave in panel": "لا تتركه في اللوحة",
  "Do not leave in panel.<cf>Store on person.": "لا تتركه في اللوحة.<cf>احتفظ به معك.",
  "Do you copy?": "هل تسمعني بوضوح؟",
  "Do you need a moment?": "هل تحتاج لبرهة من الوقت؟",
  "Don't come down here. Don't even fucking think about trying to stop me.": "إياك أن تنزل إلى هنا. ولا تفكر اللعنة حتى في محاولة إيقافي.",
  "Don't let them tempt you into surrender.": "لا تدعهم يغرونك بالاستسلام.",
  "Don't linger.": "لا تتباطأ هنا.",
  "Don't listen to their apathy.": "لا تصغِ لبرودهم ولامبالاتهم.",
  "Don’t say a word, just shut up.": "لا تنطق بحرف، فقط اصمت.",
  "Drilling department. Indicate the subject of your inquiry.": "قسم الحفر. حدد موضوع استفسارك.",
  "Due to the subjects critical condition,": "نظراً للحالة الحرجة للشخص المعني،",
  "During an on-site visit, a personal recording was collected<cf>from you.": "أثناء زيارة ميدانية، تم أخذ تسجيل شخصي<cf>منك.",
  "EMERGENCY NOTICE - CONFIDENTIAL<cf><cf>If you hear a patient who has been confirmed to be deceased speak,<cf><cf>DO NOT UNDER ANY CIRCUMSTANCES LISTEN TO WHAT THEY ARE SAYING.":
  "إشعار طوارئ - سري للغاية<cf><cf>إذا سمعت مريضاً تم تأكيد وفاته يتحدث،<cf><cf>إياك تحت أي ظرف من الظروف أن تستمع لما يقوله.",
  "EMERGENCY:<cf>801 641 88": "طوارئ:<cf>801 641 88",
  "EXPLOSIVE SYSTEM STATE": "حالة النظام المتفجر",
  "EXTERNAL CALL": "مكالمة خارجية",
  "Electricity": "الكهرباء",
  "Elena Morozova<cf>\"The Earth is not a foe - she is a challenge.\"<cf>Depth Achieved: 4287 meters<cf>March 2, 1955":
  "إيلينا موروزوفا<cf>\"الأرض ليست عدواً - إنها تحدٍّ.\"<cf>العمق المحقق: 4287 متراً<cf>2 مارس 1955",
  "Emergency": "طوارئ",
  "Emergency?": "طوارئ؟",
  "Employee ID:<cf>Age:<cf>Civil Status:<cf>Citizenship:<cf>Criminal History:": "معرف الموظف:<cf>العمر:<cf>الحالة الاجتماعية:<cf>المواطنة:<cf>السجل الجنائي:",
  "Enter the age of the person associated with this record, then press #.": "أدخل عمر الشخص المرتبط بهذا السجل، ثم اضغط #.",
  "Enter waypoint data from the LABORATORY into the terminal": "أدخل بيانات نقطة المسار من المختبر في الشاشة",
  "Estimate the severity of your current emergency from 1 - 9.": "قدّر مدى خطورة حالة الطوارئ لديك من 1 إلى 9.",
  "Even if you tried to explain what truly is at stake here for you now, would they understand?": "حتى وإن حاولت شرح ما هو على المحك حقاً بالنسبة لك هنا، فهل سيفهمون؟",
  "Even stranger, those voices all repeat the same word:": "والأغرب من ذلك، أن تلك الأصوات تردد جميعها نفس الكلمة:",
  "Even the dimmest light may pierce the darkness. Your fate is in your hands now.": "حتى أضعف خيط من الضوء قد يخترق حلكة الظلام. مصيرك بين يديك الآن.",
  "Existing Recording Found<cf><cf>Overwrite?": "تم العثور على تسجيل موجود مسبقاً<cf><cf>هل تريد استبداله والكتابة فوقه؟",
  "Express Telegram<cf><cf>From: Stepan Adamenko<cf>To: Viktor Kaminskyi<cf><cf>You have to go home right now.<cf>All landlines, electronics out of order.<cf>Fires throughout the city.<cf>Can't tell you confidential details.<cf>We have made a mistake I fear we cannot undo.":
  "برقية عاجلة<cf><cf>من: ستيبان أدامينكو<cf>إلى: فيكتور كامينسكي<cf><cf>عليك العودة إلى المنزل في هذه اللحظة.<cf>جميع الخطوط الأرضية والإلكترونيات معطلة تماماً.<cf>الحرائق تشتعل في كل أرجاء المدينة.<cf>لا يمكنني إخبارك بالتفاصيل السرية.<cf>لقد ارتكبنا خطأً أخشى ألا نتمكن من إصلاحه أبداً.",
  "External temp": "درجة الحرارة الخارجية",
  "FAMOUS GEOLOGIST MAKES GROUNDBREAKING DISCOVERY<cf>Signal found by Dr. Hrytsenko<cf><cf>Is something trying to contact us from below?<cf>\"The frequency of the Signal seems to change depending on the observer,<cf>\" Dr. Hrytsenko says:<cf>\"In plain terms, it 'speaks' in different ways depending on who's listening.\"<cf><cf>Ever since the Matryoshka Incident, most citizens of the SPRN have<cf>in some way or another experienced-":
  "جيولوجي شهير يحقق اكتشافاً مذهلاً<cf>د. هريتسينكو يعثر على الإشارة<cf><cf>هل هناك من يحاول الاتصال بنا من الأعماق؟<cf>يقول د. هريتسينكو:<cf>\"يبدو أن تردد الإشارة يتغير اعتماداً على المراقب،<cf>وبعبارات بسيطة، فهي 'تتحدث' بطرق مختلفة باختلاف من يستمع إليها.\"<cf><cf>منذ حادثة الماتريوشكا، شعر معظم مواطني الجمهورية بشكل أو بآخر بـ-",
  "FIX<cf>VENT!": "أصلح<cf>فتحة التهوية!",
  "FLOW RATE........STABLE<cf>SCRUBBERS........ONLINE<cf><cf>FAN SYSTEM IN........OK<cf>FAN SYSTEM OUT.......OK<cf>FAN SYSTEM C.........OK":
  "معدل التدفق........مستقر<cf>أجهزة التنقية........متصلة بالخدمة<cf><cf>نظام مروحة الدخول........سليم<cf>نظام مروحة الخروج.......سليم<cf>نظام المروحة ج.........سليم",
  "FORWARD STRATA DENSITY EXCEEDS CUTTING THRESHOLD.<cf>MECHANICAL DRILLING INEFFECTIVE.<cf><cf><cf><cf>REQUIRED ACTION:<cf>INITIATE TORPEDO SOFTENING PROCEDURE.<cf>":
  "كثافة الطبقات الصخرية الأمامية تتجاوز قدرة القطع.<cf>الحفر الميكانيكي غير مجدٍ.<cf><cf><cf><cf>الإجراء المطلوب:<cf>بدء عملية تليين الصخور بالطوربيد.<cf>",
  "Find Petro.": "ابحث عن بيترو.",
  "Find me": "جدني",
  "Fire": "حريق / إطلاق",
  "Fire Extinguisher": "مطفأة حريق",
  "Flashlight": "مصباح يدوي",
  "Flip switches 1, 3, 6 and 7 into the upright \"ON\" position. Switches may be stiff, apply steady pressure.": "اقلب المفاتيح 1 و 3 و 6 و 7 للأعلى إلى وضع التشغيل. قد تكون المفاتيح قاسية، اضغط بثبات.",
  "Flower": "زهرة",
  "Follow it, and I will lead you through the darkness.": "اتبعها، وسأقودك عبر عتمة الظلام.",
  "Follow my light,": "اتبع نوري،",
  "For now you will have to divert power yourself by rerouting the fusebox on the REC floor.": "في الوقت الحالي، سيتعين عليك تحويل الطاقة بنفسك عبر إعادة توجيه صندوق المصاهر في طابق الاستراحة.",
  "For tomorrow, then?": "من أجل الغد، إذن؟",
  "Found in the Geologists dorm. The faint blood on the shell a testament to forsaken dreams.": "عُثر عليه في مهجع الجيولوجي. بقع الدم الباهتة على غلافه شاهد على أحلام مهجورة ومبتورة.",
  "Found in the Geologists dorm. The teal shell is scratched with frantic, ineligible notes.": "عُثر عليه في مهجع الجيولوجي. الغلاف الفيروزي مخدوش بملاحظات هستيرية غير مقروءة.",
  "Found in the engine halls. The shell is stained with oily fingerprints.": "عُثر عليه في قاعات المحركات. الغلاف ملطخ ببصمات زيتية متسخة.",
  "Get into the cockpit. Listen to your instincts.": "ادخل إلى قمرة القيادة. واستمع لغرائزك.",
  "Get into the pilot seat, Viktor.": "اجلس في مقعد الطيار يا فيكتور.",
  "Get out of the way!": "ابتعد عن الطريق!",
  "Getting the drill moving again must be your absolute top priority.": "إعادة تشغيل الحفار وتحريكه يجب أن تكون أولويتك القصوى والمطلقة.",
  "Goodbye": "وداعاً",
  "He is not truly gone, Viktor.": "إنه لم يرحل حقاً يا فيكتور.",
  "He is still here, somewhere in this old painful memory of yours.": "إنه لا يزال هنا، في مكان ما داخل هذه الذكرى المؤلمة من ماضيك.",
  "He shouldn't have been able to get out, let alone get hold of any bullets.": "لم يكن ينبغي له أن يتمكن من الخروج، فما بالك بالحصول على أي رصاصات.",
  "He stabbed Hrytsenko multiple times with a screwdriver. Two of the wounds were fatal.": "طعن هريتسينكو عدة مرات بمفك براغي. وكان جرحان منهما قاتلين.",
  "He was adamant that Viktor wasn't himself. That it would have been wrong to kill him.": "كان مصراً على أن فيكتور لم يكن في وعيه، وأنه كان من الخطأ قتله.",
  "He was clearly delirius beyond all human reason at that point.": "كان في حالة هذيان مطبق تجاوزت كل منطق بشري في تلك المرحلة.",
  "He was one of those geniuses that felt larger than life.": "كان من أولئك العباقرة الذين تشعر أنهم أكبر من هذه الحياة.",
  "His cassette is the key. It is what will bridge the gap between us.": "كاسيته هو المفتاح. وهو ما سيبني الجسر بيننا.",
  "History doesn’t punish the guilty, it punishes the convenient.": "التاريخ لا يعاقب الجناة الحقيقيين، بل يعاقب من يسهل تحميلهم الذنب.",
  "Hit the target with a torpedo.": "أصب الهدف بطوربيد.",
  "Home.": "الوطن / المنزل.",
  "Hurry.": "أسرع.",
  "Hydraulics": "الأنظمة الهيدروليكية",
  "I Told You So": "لقد حذرتك سابقاً",
  "I asked dad if he had ever shot a gun, but he said that he hadn't.<cf>He said that there was a big war once and no one was allowed to have guns after that.":
  "سألت أبي إن كان قد أطلق النار من مسدس من قبل، فقال إنه لم يفعل.<cf>قال إن حرباً كبرى وقعت في الماضي ولم يُسمح لأحد باقتناء السلاح بعدها.",
  "I assure you, no one wants this. Especially when you are so close to the M-12 vessel.": "أؤكد لك، لا أحد يريد هذا. لا سيما وأنكم على مقربة بالغة من السفينة M-12.",
  "I can help you find what you seek.": "بوسعي مساعدتك في العثور على ما تنشده.",
  "I can't even remember her name.": "لا أكاد حتى أتذكر اسمها.",
  "I did everything I could to protect you. I really did.": "فعلت كل ما في وسعي لحمايتك. فعلت ذلك حقاً.",
  "I don't know why the neighbor's cat always yells at me.<cf>I just want to be friends.": "لا أدري لمَ تصرخ قطة الجيران في وجهي دائماً.<cf>أنا فقط أريد أن نكون أصدقاء.",
  "I don't know where it came from, I don't know what it wants.": "لا أعلم من أين أتى، ولا أعلم ماذا يريد.",
  "I don't want to be alone.": "لا أريد أن أكون وحيداً.",
  "I don't want to die.": "لا أريد أن أموت.",
  "I don’t know where one memory ends and the next one begins.": "لم أعد أميز أين تنتهي ذكرى وأين تبدأ الأخرى.",
  "I hate to say 'I told you so', Stepan.": "أكره أن أقول 'لقد حذرتك' يا ستيبان.",
  "I have EVERYTHING to lose.": "لدي كل شيء لأخسره.",
  "I have to show you what I've found.": "عليّ أن أريك ما عثرت عليه.",
  "I haven't.": "لم أفعل.",
  "I hope it can save you now.": "آمل أن ينقذك الآن.",
  "I hope this is just another Kaminskyi issue, but you MUST get him back into the cockpit.": "آمل أن تكون هذه مجرد مشكلة أخرى من مشاكل كامينسكي، ولكن عليك حتماً إعادته إلى قمرة القيادة.",
  "I just don't want to give up.": "لا أريد فقط الاستسلام.",
  "I just know it.": "أنا على يقين من ذلك فحسب.",
  "I just need to know it wasn't all for nothing.": "أحتاج فقط لأن أعرف أن كل هذا لم يكن هباءً منثوراً.",
  "I just want to be the kind of father who tries.": "أريد فقط أن أكون ذلك الأب الذي يبذل وسعه ويحاول.",
  "I know it hurts.": "أعلم كم هو مؤلم.",
  "I know the White Rabbit is disrupting most communications, but you've been at a standstill for over 12 hours now.": "أعلم أن الأرنب الأبيض يشوش معظم الاتصالات، لكنكم متوقفون تماماً منذ أكثر من 12 ساعة الآن.",
  "I know things don't seem good now.": "أعلم أن الأمور لا تبدو مبشرة الآن.",
  "I know this isn't how either of us wanted this to go, but others will pick up the torch from us.": "أعلم أن هذه ليست الطريقة التي أردناها لنهاية الأمور، لكن آخرين سيحملون الشعلة من بعدنا.",
  "I know you did all that you could.": "أعلم أنك فعلت كل ما في استطاعتك.",
  "I know you will find a way.": "أعلم أنك ستجد سبيلاً.",
  "I miss dad.": "أفتقد أبي.",
  "I never did.": "لم أفعل قط.",
  "I refuse to accept the worst.": "أرفض تصديق السيناريو الأسوأ.",
  "I refuse to cancel this mission over one drunk. Too much is at stake.": "أرفض إلغاء هذه المهمة بسبب مخمور واحد. فالكثير على المحك.",
  "I said it during the prep.": "لقد قلت ذلك أثناء مرحلة التحضير.",
  "I should have done more to protect you.": "كان ينبغي عليّ بذل المزيد لحمايتك.",
  "I should have never brought you to this godforsaken place.": "ما كان يجب عليّ أبداً أن آتي بك إلى هذا المكان الملعون.",
  "I stood by the shore and looked at the ocean.<cf>It felt really big.<cf>I kept thinking there could be huge fish or monsters under the water.<cf>Scary!":
  "وقفت عند الشاطئ ونظرت إلى المحيط.<cf>كان يبدو هائلاً حقاً.<cf>وظللت أفكر بأنه قد تكون هناك أسماك ضخمة أو وحوش تحت الماء.<cf>مخيف جداً!",
  "I suppose you are still looking for your son.": "أفترض أنك ما زلت تبحث عن ابنك.",
  "I told them from the start.": "لقد أخبرتهم منذ البداية.",
  "I told you so": "لقد حذرتكم من قبل",
  "I understand that you must feel wary to trust me.": "أتفهم أنك تشعر بالحذر والتردد في الوثوق بي.",
  "I understand the situation is dire, but that enough is not grounds for extraction.": "أتفهم أن الوضع خطير، لكن ذلك وحده ليس مبرراً كافياً للإخلاء.",
  "I want To go DeepeR DowN THan anyone": "أريد النزول لأعماق أبعد من أي أحد",
  "I want to go home": "أريد العودة إلى المنزل",
  "I want to go home.": "أريد الذهاب إلى البيت.",
  "I want to play again.": "أريد أن ألعب مرة أخرى.",
  "I was right about the signal.": "كنت على حق بشأن الإشارة.",
  "I'm afraid it gave up on your kind a long time ago.": "أخشى أنها قد يئست من بني جنسك وتخلت عنهم منذ زمن بعيد.",
  "I'm aware that Dr. Hrytsenko is the one responsible for interpreting the Signal data.": "أدرك تماماً أن الدكتور هريتسينكو هو المسؤول عن تفسير بيانات الإشارة.",
  "I'm cold.": "أشعر بالبرد.",
  "I'm glad he is with me.": "أنا سعيد لأنه بجواري.",
  "I'm not about to let your stubborness be the death of you.": "لن أدع عنادك يقودك إلى حتفك.",
  "I'm not good with words.": "لست بارعاً في انتقاء الكلمات.",
  "I'm scared.": "أنا خائف.",
  "I'm so scared": "أنا خائف جداً",
  "I'm so scared.": "أنا خائف للغاية.",
  "I'm so sorry.": "أنا آسف جداً.",
  "I'm sorry, I just don't know... I don't know what I'm doing.": "أنا آسف، أنا فقط لا أعلم... لا أعلم ما الذي أفعله.",
  "I'm still here": "ما زلت هنا",
  "I'm taking the engines apart. We're stopping here.": "أنا أقوم بتفكيك المحركات. سنتوقف هنا.",
  "I'm telling you this as a friend. If you extract now, without central command permission, heads will roll.": "أقول لك هذا كصديق. إذا انسحبتم الآن دون إذن القيادة المركزية، فستطير رؤوس كثيرة.",
  "I'm truly sorry you had to go through that again.": "أنا آسف حقاً لأنك اضطررت لمعايشة ذلك مجدداً.",
  "I've been waiting so long.": "لقد انتظرت طويلاً.",
  "I've got to say... I've never seen anything so beautiful.": "يجب أن أعترف... لم أرَ في حياتي شيئاً بهذا البهاء.",
  "ID": "المعرف الشخصي",
  "INACTIVE": "غير نشط",
  "INBOX STATUS": "حالة صندوق الوارد",
  "INCOMPATIBLE": "غير متوافق",
  "INCOMPATIBLE CASSETTE": "كاسيت غير متوافق",
  "INPUT COORDINATES": "أدخل الإحداثيات",
  "INSERT A TORPEDO INTO THE FIRING TUBE": "أدخل طوربيداً في أنبوب الإطلاق",
  "INSERT CASSETTE": "أدخل الكاسيت",
  "INSERT EMPLOYEE ID": "أدخل معرف الموظف",
  "INSERT INTO A DOOR PANEL": "أدخله في لوحة الباب",
  "INSERT KEY<cf>START ENGINES": "أدخل المفتاح<cf>لتشغيل المحركات",
  "INTERNAL CALL": "مكالمة داخلية",
  "IT AWAKES": "إنه يستيقظ",
  "IT CALLS": "إنه ينادي",
  "IT FESTERS": "إنه يتقيح ويتفاقم",
  "IT IS WAKING UP": "إنه يستيقظ الآن",
  "IT LIES": "إنه يكذب",
  "IT SMILES": "إنه يبتسم",
  "IT WAITS": "إنه يتربص وينتظر",
  "If I could bring back Petro right now for you, I would.": "لو كان بإمكاني إعادة بيترو إليك في هذه اللحظة، لفعلت دون تردد.",
  "If only we'd known...": "لو أننا فقط كنا نعلم...",
  "If there is blame in this mission, it begins and ends with me.": "إن كان ثمة لوم في هذه المهمة، فهو يبدأ وينتهي عندي.",
  "If this is correct, press 1. If this is not correct, press 2.": "إذا كان هذا صحيحاً، اضغط 1. وإن لم يكن صحيحاً، اضغط 2.",
  "If we bring you with us, then the mission is doomed.": "إذا أخذناك معنا، فإن مصير المهمة هو الهلاك المحتوم.",
  "If you are to overcome it, then you must face it head on": "إذا أردت التغلب عليه، فعليك مواجهته وجهاً لوجه",
  "Ignition": "التشغيل",
  "Ignition Key": "مفتاح التشغيل",
  "Impressive that such a small vessel can contain something as infinite as a soul.": "من المثير للدهشة أن مركبة صغيرة كهذه يمكن أن تحتوي شيئاً لا نهائياً كالروح.",
  "In Memoriam: Matvii Romaniuk<cf>1954 - 1979": "تخليداً لذكرى: ماتفي رومانيك<cf>1954 - 1979",
  "In Stepan's dorm there is a gun case. There's just a single bullet on board, for the most unthinkable of emergencies.": "في مهجع ستيبان توجد حقيبة مسدس. ولا توجد سوى رصاصة واحدة على متن السفينة، لأشد الطوارئ غير المتوقعة.",
  "In return, I merely hope to give you the peace you have so truly earned.": "في المقابل، آمل فقط أن أمنحك السلام الذي استحققتَه بحق.",
  "Inbox": "صندوق الوارد",
  "Incoming": "وارد",
  "Incompatible": "غير متوافق",
  "Input coordinates and steer to target": "أدخل الإحداثيات وقُد السفينة نحو الهدف",
  "Inscribe to a communication cassette to read": "قم بالحفر على كاسيت اتصالات لقراءته",
  "Insert Cassette": "أدخل الكاسيت",
  "Insert the fuses into the sockets.<cf>Do not force insertion, misalignment may cause shorting.": "أدخل المصاهر في المقابس.<cf>لا تستخدم القوة، فقد يؤدي عدم المحاذاة إلى التماس.",
  "Instant subtitles..........": "ترجمة فورية..........",
  "Instead they ventured beyond where your kind were ever meant to go,": "بدلاً من ذلك، تجرأوا وتوغلوا إلى ما وراء الحدود المقدرة لجنسكم،",
  "Instead you set him free.": "وبدلاً من ذلك، أطلقت سراحه وحررته.",
  "Internal call:": "مكالمة داخلية:",
  "Internal temp": "درجة الحرارة الداخلية",
  "Invert mouse...............": "عكس الماوس...............",
  "Is this everything?": "هل هذا كل شيء؟",
  "Is to be buried": "ينبغي أن يُدفن",
  "It and I were both given a chance at redemption.": "أُتيحت لي وله فرصة لنيل الخلاص والفداء.",
  "It didn't matter that you hurried home as fast as you could.": "لم يكن مهماً أنك أسرعت للمنزل بأقصى ما تستطيع.",
  "It doesn't have to be the Signal.": "ليس بالضرورة أن تكون الإشارة هي السبب.",
  "It has always been the same.": "كانت الأمور دائماً على هذا النحو.",
  "It has just given up.": "لقد استسلم للتو فحسب.",
  "It is an old, desperate creature.": "إنه مخلوق قديم يائس.",
  "It is here.": "إنه هنا.",
  "It is how you will set us both free.": "هكذا ستحررنا نحن الاثنين معاً.",
  "It is not here. <cf><cf>You are safe.<cf><cf>For now.": "إنه ليس هنا. <cf><cf>أنت في أمان.<cf><cf>في الوقت الراهن.",
  "It is waking up.": "إنه يستيقظ.",
  "It reacts to us. As we drill.": "إنه يتفاعل معنا كلما واصلنا الحفر.",
  "It seems like he tried to reason with Kaminskyi..": "يبدو وكأنه حاول التحدث بالمنطق مع كامينسكي..",
  "It seems to call to you specifically, for some reason.": "يبدو أنه يناديك أنت بالذات، لسبب ما.",
  "It wants to devour you.": "إنه يريد أن يبتلعك ويلتهمك.",
  "It will be yours.": "سيكون ملكك.",
  "It's Hrytsenko.": "إنه هريتسينكو.",
  "It's a dangerous place, but I'll help you out of this, as best I can.": "إنه مكان محفوف بالمخاطر، لكنني سأساعدك على الخروج منه بأفضل ما أستطيع.",
  "It's alive, Viktor.": "إنه كائن حي، يا فيكتور.",
  "It's been several days now since any contact from you.": "مرت عدة أيام الآن دون أي اتصال من طرفك.",
  "It's like he tried to rip his body apart.": "يبدو وكأنه حاول تمزيق جسده إرباً.",
  "It's namesake tried so desperately to glimpse the truth. If only he'd opened his eyes.": "حاول سميّه بيأس أن يلمح الحقيقة. لو أنه فتح عينيه فحسب.",
  "It's natural that you feel responsible for the crew. You are.": "من الطبيعي أن تشعر بالمسؤولية تجاه الطاقم؛ فأنت مسؤول عنهم بالفعل.",
  "It's never enough.": "لا شيء يكفي أبداً.",
  "It's not a pretty sight.": "إنه ليس منظراً يسر الناظرين.",
  "It's okay, daddy is here.": "لا بأس، والدك هنا بجوارك.",
  "Its buttons are faint from use but still responsive.": "أزراره باهتة من كثرة الاستعمال لكنها لا تزال تستجيب.",
  "Its not your job to ask why.<cf><cf>Its your job to get the crew there.": "ليس من شأنك أن تسأل عن الأسباب.<cf><cf>مهمتك هي إيصال الطاقم إلى هناك فحسب.",
  "JOIN US IN THE DEPTH<cf><cf>DO NOT RESIST": "انضم إلينا في الأعماق السحيقة<cf><cf>لا تقاوم",
  "JOIN US IN THE DEPTH<cf>BECOME A GEONAUT<cf>STRATA": "انضم إلينا في الأعماق<cf>كن بحاراً في باطن الأرض<cf>ستراتا",
  "JUDGEMENT": "حساب ودينونة",
  "Just don't look directly at the screen.": "فقط لا تنظر مباشرة إلى الشاشة.",
  "Just hand me the tapes.": "فقط سلمني الأشرطة.",
  "Just stay up there. Dig your own grave for all I care.": "فقط ابقَ هناك بالأعلى. احفر قبرك بيدك، لا أبالي.",
  "Kateryna is waiting for me.": "كاتيرينا في انتظاري.",
  "Keep following the Signal, Viktor. That is how you will find me.": "واصل اتباع الإشارة يا فيكتور. هكذا ستجدني.",
  "Keep rolling the tape.": "استمر في تدوير الشريط.",
  "Kill the monster.": "اقتل الوحش.",
  "LABORATORY": "المختبر",
  "LET HIM GUIDE YOU": "دعه يرشدك",
  "LET THERE BE LIGHT, FOR NOW": "ليكن هناك نور، في الوقت الراهن",
  "LIFE SUPPORT SYSTEMS": "أنظمة دعم الحياة",
  "LOCK IN": "تأمين الإغلاق",
  "Let me just start by saying we are all devastated about Hrytsenko's death.": "دعني أبدأ بالقول إننا جميعاً محطمون ومدمرون لوفاة هريتسينكو.",
  "Let me remind you that I am your commanding officer.": "دعني أذكرك بأنني قائدك المسؤول.",
  "Let this world without him finally be undone.": "دع هذا العالم الذي يخلو منه يزول وينهار أخيراً.",
  "Let's get this over with.": "دعنا ننهي هذا الأمر ونفرغ منه.",
  "Like Petro I still live on, trapped in static.": "مثل بيترو، ما زلت أحيا، حبيس التشويش والأثير.",
  "Like water breaks stone over the ages.": "كما تفتت المياه الصخر على مر العصور.",
  "Liliya and Vira are waiting for me.": "ليليا وفيرا تنتظرانني.",
  "Listen. Viktor, listen to me.": "استمع إليّ. يا فيكتور، أنصت لي.",
  "Look at me. It's time I made you see.": "انظر إليّ. حان الوقت لكي أجعلك تبصر الحقيقة.",
  "Look, I know that thing that got Yosep and Bohdan is still here with us.": "اسمع، أعلم أن ذلك الكائن الذي نال من يوسف وبوهدان لا يزال هنا معنا.",
  "Look, I'm not trying to be heartless. All I'm saying is that this is not one of those situations I can bail you out from.": "انظر، لا أحاول أن أكون خالية من الرحمة. كل ما أقوله هو أن هذا ليس من تلك المواقف التي أستطيع إخراجك منها.",
  "Loyalty doesn’t tend to be rewarded in this business.": "الوفاء ليس مما يُكافأ عليه المرء عادة في هذا المجال.",
  "M-13,<cf>I'm sorry to say it, but this mission is a disaster.": "M-13،<cf>يؤسفني قول هذا، لكن هذه المهمة كارثة محققة.",
  "M-13,<cf>Maria here.": "M-13،<cf>ماريا هنا.",
  "M-13,<cf>This is Maria,<cf>Surface Control.": "M-13،<cf>معكم ماريا،<cf>مركز التحكم السطحي.",
  "M-13,<cf>Whoever is reading this...": "M-13،<cf>أياً كان من يقرأ هذه الرسالة...",
  "M.O.L.E": "إم.أو.إل.إي (الحفارة)",
  "MAKE THE RECORDING<cf>PRESS THE SWITCH": "قم بالتسجيل<cf>اضغط على المفتاح",
  "MANUAL PILOTING NEEDS TO BE ENGAGED.<cf><cf>ENTER 4-DIGIT EMPLOYEE ID <cf>FROM YOUR ISSUED DORM CASSETTE.<cf><cf>Y = FIRST 2 DIGITS <cf>X = LAST 2 DIGITS":
  "يلزم تفعيل القيادة اليدوية.<cf><cf>أدخل الرقم التعريفي للموظف المكون من 4 أرقام <cf>من كاسيت المهجع المخصص لك.<cf><cf>Y = أول رقمين <cf>X = آخر رقمين",
  "Make that shot count.": "اجعل تلك الطلقة تصيب هدفها بدقة.",
  "Make the VOSTOK bank transaction.": "أجرِ المعاملة المصرفية لفوستوك.",
  "Make the recording.": "قم بإجراء التسجيل.",
  "Make your first course correction.": "أجرِ أول تصحيح للمسار.",
  "Make your way over to us, yeah?": "شق طريقك نحونا، حسناً؟",
  "Merely a flimsy ward against the darkness they sent you into.": "مجرد تميمة واهية ضد الظلام الذي أرسلوك إليه.",
  "Move the M-12 Vessel.": "حرّك السفينة M-12.",
  "NAV-04": "الملاحة-04",
  "NAVIGATION LOCKED": "الملاحة مقفلة",
  "NEURAL STIMUALTOR": "المحفز العصبي",
  "NEURAL STIMULATION": "التحفيز العصبي",
  "NO ACTIVE WAYPOINT IS SET<cf><cf>RETRIEVE WAYPOINT DATA FROM THE LABORATORY": "لم يتم تعيين أي نقطة مسار نشطة<cf><cf>استرجع بيانات المسار من المختبر",
  "NO CASSETTE FOUND": "لم يتم العثور على أي كاسيت",
  "NO CASSETTE INSERTED": "لا يوجد كاسيت مدرج",
  "NO DATA ENCODED<cf><cf>INSERT A NEURAL CASSETTE<cf>WITH A GEO LAB RECORDING": "لا توجد بيانات مسجلة<cf><cf>أدخل كاسيتاً عصبياً<cf>يحوي تسجيلاً من مختبر الجيولوجيا",
  "NO INSERTED CASSETTE": "لا يوجد كاسيت مدرج",
  "NO NAVIGATION<cf>CASSETTE FOUND": "لم يتم العثور على<cf>كاسيت ملاحة",
  "NO NEW ORDERS": "لا توجد أوامر جديدة",
  "NO WAYPOINT DATA": "لا توجد بيانات مسار",
  "NOT DEAD YET": "لم يمت بعد",
  "NOT ENGAGED": "غير معشق",
  "NOT READABLE": "غير قابل للقراءة",
  "NOT READY": "غير جاهز",
  "Navigating through the layers below you is far too precise for our instruments. We can't risk another Matryoshka incident.": "الملاحة عبر الطبقات التي أسفلكم دقيقة للغاية بالنسبة لأجهزتنا. لا يمكننا المخاطرة بحادثة ماتريوشكا أخرى.",
  "Need room to be dark.": "الغرفة بحاجة لأن تكون مظلمة.",
  "Negative. We believe he was the first one Kaminskyi killed.": "سلبي. نعتقد أنه كان أول شخص قتله كامينسكي.",
  "Neural Cassette": "كاسيت عصبي",
  "New Assignment": "مهمة جديدة",
  "No account is registered under that ID. Please try again.": "لا يوجد حساب مسجل بهذا المعرف. يرجى المحاولة مرة أخرى.",
  "No one is coming.": "لن يأتي أحد لإنقاذكم.",
  "No wonder you were broken.": "لا عجب أنك كنت محطماً.",
  "Nothing lies between us now.": "لم يعد هناك ما يقف حائلاً بيننا الآن.",
  "Now for the bad news.": "والآن إلى الأخبار السيئة.",
  "Now you are close. Very close.": "أنت الآن قريب. قريب للغاية.",
  "Now you have to hurry.": "عليك الآن الإسراع فوراً.",
  "Now, for the M-12 vessel... This is where things get truly weird.": "والآن، بالنسبة للسفينة M-12... هنا تصبح الأمور غريبة حقاً.",
  "O2 LEVEL": "مستوى الأكسجين",
  "ON TRACK": "على المسار الصحيح",
  "ONE LAST TIME": "للمرة الأخيرة",
  "ORDER INSCRIBED": "تم حفر الأمر وتسجيله",
  "Of course it’s you.": "بالطبع إنه أنت.",
  "Of course we both know the truth is a bit more complicated than that.": "بالطبع كلينا يعلم أن الحقيقة أكثر تعقيداً من ذلك بقليل.",
  "Oh Saints... Stepan.": "يا للقديسين... يا ستيبان.",
  "Oh, Viktor.": "آه يا فيكتور.",
  "Oh, how long I too had waited.": "آه، كم انتظرت أنا أيضاً طويلاً.",
  "One last time.": "للمرة الأخيرة.",
  "Open your eyes, Navigator.<cf><cf>The Mole is blind without you.": "افتح عينيك أيها الملاّح.<cf><cf>الحفار أعمى من دونك.",
  "Or I'll put a screwdriver through your skull.": "وإلا سأغرس مفك براغي في جمجمتك.",
  "Or Saints help me, there will be consequences if you actually make it back to the surface.": "والقديسون يشهدون، ستكون هناك عواقب وخيمة إن تمكنت حقاً من العودة للسطح.",
  "Otherwise you'll be boiled alive in a few hours.": "وإلا فستُطبخ حياً في غضون بضع ساعات.",
  "Otherwise you'll be digging blindly.": "وإلا فستحفر في الظلام خبط عشواء.",
  "Our communication windows are getting narrower. At least, that's what I hope is happening.": "نوافذ الاتصال بيننا تضيق باستمرار. على الأقل، هذا ما آمل أنه يحدث.",
  "Our records indicate that the payment has not yet been finalized and requires your registration consent.": "تشير سجلاتنا إلى أن الدفع لم يكتمل بعد ويتطلب موافقتك على التسجيل.",
  "Our systems have lost track of the Signal again.": "فقدت أنظمتنا أثر الإشارة مجدداً.",
  "PLACE THE PRIMER OVER THE TUBE AND COCK IT": "ضع الصاعق فوق الأنبوب وقم بتجهيزه",
  "PLEASE INSERT A CASSETTE...": "يرجى إدخال الكاسيت...",
  "POINT BLANK": "من مسافة الصفر",
  "PRESS THE BUTTON TO<cf>INSCRIBE A MESSAGE": "اضغط على الزر<cf>لتسجيل رسالة",
  "PULL LEVER<cf>TO RECORD": "اسحب الذراع<cf>لبدء التسجيل",
  "PULL HANDLE TO THE RIGHT<cf>INPUT COORDINATES<cf>": "اسحب المقبض إلى اليمين<cf>لإدخال الإحداثيات<cf>",
  "People they have lost.": "أناس فقدوهم.",
  "Perhaps I've been too informal during these messages.": "ربما كنت غير رسمية أكثر من اللازم أثناء هذه الرسائل.",
  "Petro has already waited long enough.": "لقد انتظر بيترو بالفعل بما فيه الكفاية.",
  "Petro is still with you on your vessel.": "بيترو لا يزال معك على متن سفينتك.",
  "Please be safe down there. <cf><cf>This is the last time.<cf>You promised.": "أرجوك ابقَ في أمان في الأسفل. <cf><cf>هذه آخر مرة.<cf>لقد وعدتني بذلك.",
  "Please direct your request through the proper channels.": "يرجى توجيه طلبك عبر القنوات الرسمية المناسبة.",
  "Poor bastards...": "المساكين البؤساء...",
  "Post-procedure documentation will be finalized automatically.": "سيتم إنهاء توثيق ما بعد الإجراء تلقائياً.",
  "Preservation is not an act of denial, it is an act of care.": "الحفظ ليس ضرباً من الإنكار، بل هو أسمى درجات الاهتمام والرعاية.",
  "Pull down the breaker lever with a firm motion.": "اسحب ذراع القاطع إلى الأسفل بحركة حازمة.",
  "R ENGINE:": "المحرك الأيمن:",
  "RE: Concerns": "رد: بخصوص المخاوف",
  "RE: Emergency": "رد: حالة طوارئ",
  "READABLE DATA": "بيانات مقروءة",
  "READING": "جارٍ القراءة",
  "READING SIGNAL...": "جارٍ قراءة الإشارة...",
  "READY TO INSCRIBE": "جاهز للتسجيل",
  "READY TO RECORD": "جاهز للتسجيل",
  "READY TO REMOVE": "جاهز للإزالة",
  "RECORDING FAILED<cf>TRY AGAIN": "فشل التسجيل<cf>حاول مجدداً",
  "RECORDING SUCCESSFUL": "تم التسجيل بنجاح",
  "REMEMBER": "تذكّر",
  "REMOVE INSERTED OBJECT": "أزل الجسم المدرج",
  "REPAIR THE RIGHT ENGINE MANUALLY": "أصلح المحرك الأيمن يدوياً",
  "REPORT 03/03-79<cf><cf>We finally managed to pick up readings of the Signal. <cf><cf>It's weak, but it's definitively something there with its own signature.<cf><cf>Good to know we didn't drill all this way for nothing.":
  "تقرير 03/03-79<cf><cf>تمكنا أخيراً من التقاط قراءات للإشارة. <cf><cf>إنها ضعيفة، لكن من المؤكد أن هناك شيئاً ما له بصمته الفريدة الخاصة.<cf><cf>من الجيد أن نعلم أننا لم نحفر كل هذه المسافة بلا طائل.",
  "REPORT 07/4-79<cf><cf>Signal's strength keeps rising the closer we get. <cf>Like something's waking up. <cf><cf>Not liking it one bit, but surface <cf>control asks us to keep going. <cf>They say we're going to make<cf>history. <cf><cf>I just hope it's not the cautionary kind.":
  "تقرير 07/4-79<cf><cf>قوة الإشارة تتصاعد باستمرار كلما اقتربنا. <cf>وكأن شيئاً ما يستيقظ من سباته. <cf><cf>الأمر لا يعجبني على الإطلاق، لكن مركز التحكم السطحي <cf>يطلب منا الاستمرار. <cf>يقولون إننا سنصنع<cf>التاريخ. <cf><cf>آمل فقط ألا نكون عبرة للتاريخ.",
  "REPORT 09/4-79<cf><cf>Something is making us sick. Nausea, headaches, and <cf>wounds appearing seemingly out of nowhere. <cf><cf>Radiation <cf>shields are still at full capacity, so that's not it. <cf>Radiation sickness typically doesn't make you hear voices.<cf><cf>We have requested evacuation.<cf>Some things should clearly stay buried.":
  "تقرير 09/4-79<cf><cf>هناك شيء ما يصيبنا بالمرض والوهن. غثيان وصداع <cf>وجروح تظهر دون سبب واضح. <cf><cf>دروع الإشعاع <cf>لا تزال تعمل بكامل طاقتها، إذن فليس الإشعاع هو السبب. <cf>مرض الإشعاع عادة لا يجعلك تسمع أصواتاً وهمية في رأسك.<cf><cf>لقد طلبنا الإخلاء فوراً.<cf>هناك أمور واضحة يجب أن تظل مدفونة.",
  "REPORT ?? ????<cf><cf>We have cut the extraction cables. <cf><cf>Thinking, talking <cf>getting difficult. <cf><cf>There is something here with us. <cf>It must stay here. <cf>We must stay here. <cf><cf>Just wish I remebered why.":
  "تقرير ?? ????<cf><cf>لقد قطعنا كابلات الإخلاء وسحب السفينة. <cf><cf>التفكير والكلام <cf>يصبحان بالغي الصعوبة. <cf><cf>هناك شيء ما هنا معنا. <cf>ويجب أن يبقى هنا. <cf>ويجب أن نبقى هنا معه. <cf><cf>أتمنى فقط لو كنت أتذكر السبب.",
  "RESPONSIBILITIES: DIG<cf>- DIG<cf>- DIG<cf>- DIG<cf>- DIG<cf>- DIG": "المسؤوليات: الحفر<cf>- الحفر<cf>- الحفر<cf>- الحفر<cf>- الحفر<cf>- الحفر",
  "RESPONSIBILITIES: ENGINEER<cf>- Maintain vessel engines<cf>- Monitor magnetism generator<cf>- Repairs and general maintainance":
  "مسؤوليات المهندس:<cf>- صيانة محركات السفينة<cf>- مراقبة مولد المغناطيسية<cf>- الإصلاحات والصيانة العامة",
  "RESPONSIBILITIES: GEOLOGIST<cf>- Perform Signal recordings<cf>- Evaluate Signal data<cf>- Collect rare earth samples":
  "مسؤوليات الجيولوجي:<cf>- إجراء تسجيلات الإشارة<cf>- تقييم بيانات الإشارة<cf>- جمع عينات من العناصر الأرضية النادرة",
  "RESPONSIBILITIES: NAVIGATOR<cf>- Drill Vessel Piloting<cf>- Find your son<cf>- Do whatever it takes to bring him back":
  "مسؤوليات الملاّح:<cf>- قيادة سفينة الحفر<cf>- العثور على ابنك<cf>- فعل كل ما يتطلبه الأمر لإعادته",
  "RESPONSIBILITIES: NAVIGATOR<cf>- Drill Vessel Piloting<cf>- Navigational Course Corrections<cf>- Fill in for dead crewmates<cf>- Keep the drill running, no matter what":
  "مسؤوليات الملاّح:<cf>- قيادة سفينة الحفر<cf>- تصحيح المسار الملاحي<cf>- الحلول محل الزملاء الموتى<cf>- إبقاء الحفار يعمل، مهما كلف الثمن",
  "RESTART TERMINAL": "إعادة تشغيل الشاشة",
  "ROOT://ADMIN> Critical error.": "ROOT://ADMIN> خطأ حرج.",
  "ROOT://ADMIN> Get into the pilot seat, Navigator. Reach the other side.": "ROOT://ADMIN> اجلس في مقعد الطيار أيها الملاّح. واعبر إلى الجانب الآخر.",
  "ROOT://ADMIN> Required Action: bring drilling vessel closer to Signal Source.": "ROOT://ADMIN> الإجراء المطلوب: تقريب سفينة الحفر من مصدر الإشارة.",
  "ROOT://ADMIN> Signal Source too far away from recorder.": "ROOT://ADMIN> مصدر الإشارة بعيد للغاية عن جهاز التسجيل.",
  "Reach your apartment.": "صل إلى شقتك.",
  "Record me onto the cassette together with Petro.": "سجلني على الكاسيت مع بيترو.",
  "Record my essence onto Petro's cassette.": "سجل جوهري وكياني على كاسيت بيترو.",
  "Remarkable, in some sense, that Kaminskyi still managed to get them to the M-12 vessel.": "من المثير للدهشة بنحو ما أن كامينسكي نجح رغم كل شيء في إيصالهم إلى السفينة M-12.",
  "Remember we're all depending on you.": "تذكر أننا جميعاً نعتمد عليك.",
  "Repair the engine.": "أصلح المحرك.",
  "Reply to health report": "الرد على التقرير الصحي",
  "Restore Defaults": "استعادة الإعدادات الافتراضية",
  "Right now you are far too off course for the autopilot to keep up without a navigator.": "أنتم الآن خارج المسار بدرجة كبيرة تعجز الطيار الآلي عن تداركها دون ملاّح.",
  "Rotate the middle selector knob to match the amount of fuses installed.": "أدر مفتاح التحديد الأوسط ليطابق عدد المصاهر المثبتة.",
  "Rust and blood mix along the shaft. The only reward for years of service.": "يمتزج الصدأ والدم على طول المقبض. المكافأة الوحيدة لسنوات من الخدمة.",
  "SAFE DISTANCE REACHED<cf>CLEAR OF HAZARD<cf><cf>TURN OFF VESSEL": "تم الوصول لمسافة الأمان<cf>في مأمن من الخطر<cf><cf>أوقف محرك السفينة",
  "SEISMIC PULSE: 0.02Hz <cf>TREMOR ACTIVITY:   LOW  <cf>WAVE PATTERN:      STABLE  <cf>LAST EVENT:        02:13:45  <cf>MICROTREMOR DETECTED  <cf><cf><cf><cf>MONITOR RANGE:     0-500m RADIUS  <cf>DETECTION STATUS:  ACTIVE  <cf>CALIBRATION:       VERIFIED<cf><cf><cf><cf>>> NO SIGNIFICANT ACTIVITY DETECTED":
  "النبض الزلزالي: 0.02 هرتز <cf>نشاط الهزات: منخفض <cf>نمط الموجة: مستقر <cf>آخر حدث: 02:13:45 <cf>تم رصد هزة متناهية الصغر <cf><cf><cf><cf>نطاق المراقبة: نصف قطر 0-500 متر <cf>حالة الرصد: نشطة <cf>المعايرة: مؤكدة<cf><cf><cf><cf>>> لم يتم رصد أي نشاط بارز",
  "SIGNAL ACTIVE": "الإشارة نشطة",
  "SIGNAL SOURCE": "مصدر الإشارة",
  "SIGNAL TOO WEAK": "الإشارة ضعيفة للغاية",
  "SIGNAL TOO WEAK<cf><cf>RECORDING NOT<cf>POSSIBLE": "الإشارة ضعيفة جداً<cf><cf>التسجيل غير<cf>ممكن",
  "SOURCE OF MASSIVE<cf>BLACKOUTS DISCOVERED<cf><cf>Signal found by Dr.Hrytsenko": "اكتشاف مصدر انقطاع<cf>التيار الكهربائي الهائل<cf><cf>د. هريتسينكو يعثر على الإشارة",
  "SPRN<cf>Socialist People’s Republic of Navriska<cf><cf>Signature: Petro<cf><cf>Issued on: 23 July 1978<cf>Valid until: 23 July 1988<cf><cf>Surname: Kaminskyi<cf>Name: Petro<cf>Date of birth: 02 January 1974<cf>Sex: M<cf>Place of birth: Voryslav":
  "جمهورية نافريسكا الشعبية الاشتراكية<cf><cf>التوقيع: بيترو<cf><cf>تاريخ الإصدار: 23 يوليو 1978<cf>صالح حتى: 23 يوليو 1988<cf><cf>اللقب: كامينسكي<cf>الاسم: بيترو<cf>تاريخ الميلاد: 02 يناير 1974<cf>الجنس: ذكر<cf>محل الميلاد: فوريسلاف",
  "SYSTEM FAULT<cf><cf>PROCESS INTERRUPTED<cf>MEMORY INDEX FAILURE<cf>DISPLAY DRIVER NOT RESPONDING": "خطأ في النظام<cf><cf>توقفت العملية<cf>فشل فهرس الذاكرة<cf>مشغل العرض لا يستجيب",
  "SYSTEM RESET DUE TO STATE CORRUPTION<cf><cf>NEW PASSWORD GENERATED.<cf>CHECK INTERNAL MAIL.": "إعادة ضبط النظام بسبب تلف الحالة<cf><cf>تم إنشاء كلمة مرور جديدة.<cf>افحص البريد الداخلي.",
  "Save us both before this all falls apart.": "أنقذنا معاً قبل أن ينهار كل شيء.",
  "Scavenged from a corpse. The cold truth of the world is that for some it's simply too late.": "انتُشلت من جثة هامدة. حقيقة هذا العالم القاسية هي أنه بالنسبة للبعض، فات الأوان ببساطة.",
  "Seismic data encoded.<cf>Take out cassette.": "تم تشفير البيانات الزلزالية.<cf>أخرج الكاسيت.",
  "Seismic data found.": "تم العثور على بيانات زلزالية.",
  "Sender: Maria<cf><cf>Let me just start by saying we are all devastated about Hrytsenko's death. <cf><cf>He was one of those geniuses that felt larger than life. Like we existed at a different wavelength from him. <cf><cf>But that doesn't change anything, Stepan. You have to keep going, no matter what.":
  "المرسل: ماريا<cf><cf>دعني أبدأ بالقول إننا جميعاً محطمون لوفاة هريتسينكو. <cf><cf>كان عبقرياً استثنائياً، وكأننا كنا نعيش على طول موجي مختلف عنه تماماً. <cf><cf>لكن ذلك لا يغير شيئاً يا ستيبان. عليك أن تواصل السير، مهما كانت العواقب.",
  "Set your son free.": "حرر ابنك وأطلق سراحه.",
  "Shh,  I know.": "اششش، أنا أعلم.",
  "Signal Strength": "قوة الإشارة",
  "Signal exposure leaves imprint on retina.": "التعرض للإشارة يترك بصمة وأثراً على شبكية العين.",
  "Since when has anything worthwhile ever been easy?": "منذ متى كان أي شيء ذو قيمة سهلاً؟",
  "So Kaminskyi used the old war torpedoes to blast his way in through the hull.": "إذن استخدم كامينسكي طوربيدات الحرب القديمة ليشق طريقه عبر الهيكل.",
  "So that I can bring him back to you.": "حتى أتمكن من إعادته إليك.",
  "Some kids were mean to me at kindergarten today.<cf>They laughed at me and didn’t let me play.<cf>I felt really sad and wanted to go home.<cf>Dad is never mean.":
  "كان بعض الأطفال قساة معي في الروضة اليوم.<cf>ضحكوا عليّ ولم يدعوني ألعب معهم.<cf>شعرت بحزن شديد وأردت العودة للمنزل.<cf>أبي لا يقسو عليّ أبداً.",
  "Some things just can't be solved.": "بعض الأمور لا يمكن حلها ببساطة.",
  "Soon the wait is over.": "قريباً سينتهي الانتظار.",
  "Stabilizers": "الموازنات / أجهزة التثبيت",
  "Standard pack. Crew-issued comfort, always running low.": "عبوة قياسية مخصصة لراحة الطاقم، توشك على النفاد دائماً.",
  "Standard pack. One of the few indulgencies Strata would grant you.": "عبوة قياسية. إحدى وسائل الترفيه القليلة التي تمنحك إياها ستراتا.",
  "Step 1: Fuse Installation": "الخطوة 1: تركيب المصاهر",
  "Step 2: Load Calibration": "الخطوة 2: معايرة الحمل",
  "Step 3: Circuit Activation": "الخطوة 3: تنشيط الدائرة",
  "Step 4: Phase Alignment": "الخطوة 4: محاذاة الطور",
  "Step 5: Main Breaker Engage": "الخطوة 5: تعشيق القاطع الرئيسي",
  "Stepan should have shot him.": "كان ينبغي على ستيبان أن يطلق النار عليه.",
  "Stepan was desperate to find something in Yosep's research that could help, even after the killing.": "كان ستيبان يائساً للعثور على أي شيء في أبحاث يوسف يمكن أن يساعد، حتى بعد مقتله.",
  "Still asleep in the static.": "لا يزال نائماً في غمرة التشويش.",
  "Storage": "المستودع / التخزين",
  "Stores and syncs crew mail transmissions. Assigned to Administrators.": "يخزن ويزامن رسائل بريد الطاقم. مخصص للمسؤولين الإداريين.",
  "Strata disabled the autopilot systems.": "قامت ستراتا بتعطيل أنظمة الطيار الآلي.",
  "Strata had refused to let the drilling missions be a thing of the past.": "رفضت ستراتا أن تصبح مهام الحفر العميقة جزءاً من الماضي.",
  "Strata will claim the mission failed because of sabotage.": "ستدعي ستراتا أن المهمة فشلت بسبب عمل تخريبي.",
  "Survive the monster.": "انجُ من الوحش.",
  "TAKE THE CASSETTE": "خذ الكاسيت",
  "TAPE #1": "الشريط #1",
  "TAPE #2": "الشريط #2",
  "TAPE #3": "الشريط #3",
  "TAPE #4": "الشريط #4",
  "TEMPERATURE REPORT": "تقرير درجات الحرارة",
  "THAT'LL DO": "هذا سيفي بالغرض",
  "THE BRIGHTEST MINDS<cf><cf>BELONG BELOW": "ألمع العقول<cf><cf>مكانها في الأعماق",
  "Take the cassette<cf><cf>You will need it": "خذ الكاسيت<cf><cf>سوف تحتاجه",
  "Take the cassette. Hold him in your arms and you will know.": "خذ الكاسيت. ضمه بين ذراعيك وحينها ستعلم.",
  "Taras Kaminskyi<cf>Depth Achieved: 6482m<cf>January 5, 1960": "تاراس كامينسكي<cf>العمق المحقق: 6482 متراً<cf>5 يناير 1960",
  "Thank you K-A-M-I-N-S-K-Y-I for registering with Vostok.": "شكراً لك ك-ا-م-ي-ن-س-ك-ي لتسجيلك لدى فوستوك.",
  "Thank you for keeping our hopes alive.": "شكراً لك على إبقاء آمالنا حية.",
  "Thank you for sharing that with us.": "شكراً لمشاركتك ذلك معنا.",
  "Thank you for taking this step.": "شكراً لاتخاذك هذه الخطوة.",
  "Thank you, Viktor. For all that you've given me.": "شكراً لك يا فيكتور، على كل ما قدمته لي.",
  "Thank you. The date is correct.": "شكراً لك. التاريخ صحيح.",
  "Thank you. The information is correct.": "شكراً لك. المعلومات صحيحة.",
  "That explosion just now, that was you, wasn't it?": "ذلك الانفجار للتو، كان من فعلك، أليس كذلك؟",
  "That said, we're sure glad to have you here.": "رغم ذلك، نحن سعداء للغاية بوجودك هنا معنا.",
  "That was nothing but a creature of the past.": "لم يكن ذلك سوى كائن من مخلفات الماضي.",
  "That’s what you are.": "هذا ما أنت عليه حقاً.",
  "The Cornerstone<cf><cf>8754 METERS - A NEW LOW<cf><cf>S. Adamenko<cf>": "حجر الزاوية<cf><cf>8754 متراً - قاع قياسي جديد<cf><cf>س. أدامينكو<cf>",
  "The Engineer mistook mourning for madness. He couldn't fathom what truly defines a monster.": "خلط المهندس بين الحزن والجنون. وعجز عن إدراك ما يحدد هوية الوحش حقاً.",
  "The Geologist saw the world only in waking dreams. Not realizing that to listen you have cease talking.": "رأى الجيولوجي العالم فقط في أحلام اليقظة، دون أن يدرك أنه لكي تصغي عليك أولاً أن تكف عن الكلام.",
  "The M-13 was so beat up at that point that they couldn't peform any conventional docking manuevers.": "كانت السفينة M-13 متهالكة للغاية في تلك النقطة لدرجة عجّزتهم عن إجراء أي مناورة رسو تقليدية.",
  "The Signal target coordinates seem to have been updated without issue.": "يبدو أن إحداثيات هدف الإشارة قد حُدثت دون أي مشاكل.",
  "The Signal's source. It's here, just a few meters beneath us.": "مصدر الإشارة. إنه هنا، على بعد بضعة أمتار فقط أسفلنا.",
  "The age has been verified.": "تم التحقق من العمر.",
  "The angel refused the cruelty of fate; he shattered the boundaries <cf>between life and death.": "رفض الملاك قسوة القدر؛ فحطم الحواجز <cf>بين الحياة والموت.",
  "The angel taught truth<cf>and secrets; only she <cf>truly understood.": "علّم الملاك الحقائق<cf>والأسرار؛ وحدها هي <cf>من فهمت حقيقة الأمر.",
  "The angel was imprisoned beneath <cf>the earth; the knowledge he had given them became his chains.": "حُبس الملاك في جوف <cf>الأرض؛ وصارت المعرفة التي وهبهم إياها قيوداً كبلته.",
  "The date entered is incorrect. Please try again.": "التاريخ المدخل غير صحيح. يرجى المحاولة مرة أخرى.",
  "the day scheduled for the inscription procedure is tomorrow.": "الموعد المحدد لإجراء الحفر العصبي هو الغد.",
  "The earthquakes, the constant blackouts, the fucking dead who won't shut up.": "الزلازل، والانقطاع المتواصل للكهرباء، والأموات الملعونون الذين لا يكفون عن الحديث.",
  "The extraction process has begun.": "بدأت عملية السحب والإخلاء.",
  "The filament inside looks intact. Clean contact points, no signs of stress.": "السلك الداخلي يبدو سليماً. نقاط التلامس نظيفة ولا تظهر عليها علامات إجهاد.",
  "The first recording starts right at entering the M-13 after extraction.": "يبدأ التسجيل الأول فور الدخول إلى M-13 بعد عملية الإخلاء.",
  "The following information is absolutely critical:": "المعلومات التالية بالغة الأهمية والحرج:",
  "The frequency doesn't play nice with our instruments.": "التردد يعيث فساداً في أجهزتنا ولا يستقر معها.",
  "The funds will be drawn from your bank account within one to three working days.": "سيتم سحب الأموال من حسابك المصرفي في غضون يوم إلى ثلاثة أيام عمل.",
  "The mission is cancelled. They are bringing us home.": "أُلغيت المهمة. إنهم يعيدوننا إلى الوطن.",
  "The old crew was long gone, no surprises there, but Kaminskyi did manage to use their recording equipment.": "الطاقم القديم رحل منذ زمن طويل دون مفاجأة، لكن كامينسكي نجح في استخدام معدات تسجيلهم.",
  "The past lies buried down here, Viktor.": "الماضي يرقد مدفوناً هنا في الأسفل يا فيكتور.",
  "The past that binds us both can be washed away.": "الماضي الذي يقيد كلينا يمكن غسله ومحوه.",
  "The payment has been authorized.": "تمت الموافقة على الدفع وتصريحه.",
  "The prize that sent Strata tumbling down this rabbit hole. A glimmering chain that binds us all.": "الجائزة التي أسقطت ستراتا في جحر الأرنب هذا. قيد لامع يكبلنا جميعاً.",
  "The symptoms the crew are experiencing could very well be because you are several kilometers below the surface.": "الأعراض التي يعاني منها الطاقم قد تكون بكل بساطة بسبب وجودكم على عمق عدة كيلومترات تحت السطح.",
  "The thing that hunts you thrives in the dark, as evil tends to do.": "الشيء الذي يطاردكم يترعرع في العتمة، كما هي عادة الشرور.",
  "The total amount due is 39.000.000 Zev.": "المبلغ الإجمالي المستحق هو 39,000,000 زيف.",
  "There are old, sinister things down here that might be best left forgotten.": "هناك كائنات وشرور قديمة هنا في الأسفل لعل الأفضل تركها منسية في طي الكتمان.",
  "There is something with us here. On the vessel.": "هناك شيء ما معنا هنا، على متن السفينة.",
  "There seems to have been something with Pluzhnik that really set Kaminskyi off.": "يبدو أن هناك أمراً ما مع بلوجنيك أثار غضب كامينسكي وجنونه.",
  "These are the cries from the river of souls.": "هذه صرخات ونحيب نهر الأرواح.",
  "They broke me, Viktor.": "لقد حطموني يا فيكتور.",
  "They called it the Matryoshka incident.": "أطلقوا عليها حادثة الماتريوشكا.",
  "They feared a world unaligned with<cf>the tyranny of their dogma; <cf>thus the angel was condemned, <cf>and cast down.": "خشوا عالماً لا يتماشى مع<cf>طغيان عقائدهم الجامدة؛ <cf>وهكذا أُدين الملاك، <cf>وطُرح في الهاوية.",
  "They pray blindly for salvation.": "إنهم يتضرعون بعمى التماساً للخلاص.",
  "They will never truly trust you, Viktor.": "لن يثقوا بك ثقة حقيقية أبداً يا فيكتور.",
  "They'll get us out, we just have to give them some time.": "سيخرجوننا من هنا، علينا فقط إمهالهم بعض الوقت.",
  "This ID is associated with the name P-E-T-R-O.": "هذا المعرف مرتبط بالاسم ب-ي-ت-ر-و.",
  "This call serves as verification.": "هذه المكالمة بمثابة تحقق وتأكيد.",
  "This case is only to be opened if met with an insurmountable emergency.<cf><cf>All crew members need to unanimously agree to open this case. Therefore each crew member has been assigned one digit at random.<cf><cf>May god help you.<cf><cf>– STRATA<cf><cf>digit three: 5":
  "لا تُفتح هذه الحقيبة إلا عند مواجهة حالة طوارئ مستعصية.<cf><cf>يجب أن يوافق جميع أفراد الطاقم بالإجماع على فتحها. ولذلك تم تخصيص رقم واحد عشوائياً لكل فرد.<cf><cf>كان الله في عونكم.<cf><cf>– ستراتا<cf><cf>الرقم الثالث: 5",
  "This cassette is the key. You brought it with you on this mission for a reason.": "هذا الكاسيت هو المفتاح. لقد أحضرته معك في هذه المهمة لسبب وجيه.",
  "This game contains disturbing imagery, including themes of mental illness and child death.<cf><cf>This is a fictional scenario and does not depict any real country, people, or events.<cf><cf>It features flashing lights that may trigger seizures in players with photosensitive epilepsy.<cf><cf><cf>Player discretion is advised.":
  "تحتوي هذه اللعبة على مشاهد وصور مزعجة، بما في ذلك موضوعات تتعلق بالمرض النفسي ووفاة الأطفال.<cf><cf>هذا سيناريو خيالي بالكامل ولا يمثل أي بلد أو أشخاص أو أحداث حقيقية.<cf><cf>كما تتضمن اللعبة أضواء وامضة قد تسبب نوبات صرع لدى اللاعبين المصابين بالصرع الحساس للضوء.<cf><cf><cf>يُنصح بتوخي الحذر وتقدير اللاعب.",
  "This has been all about damage control from the start.": "كان الأمر برمته مجرد محاولة للحد من الأضرار منذ البداية.",
  "This is Stepan.": "معكم ستيبان.",
  "This is Vessel M-12. Well. What remains of her.": "هذه هي السفينة M-12. حسناً، ما تبقى من حطامها بالأحرى.",
  "This is also a gentle reminder that ALL ship systems are dependent on the power that is generated by the drill itself. Including temperature control.":
  "هذا أيضاً تذكير لطيف بأن جميع أنظمة السفينة تعتمد على الطاقة المولدة من الحفار نفسه، بما في ذلك التحكم بدرجة الحرارة.",
  "This is as far as those who came before you made it.": "هذا أقصى ما وصل إليه من سبقوكم.",
  "This is my light, Viktor. At least what remains of it.": "هذا نوري يا فيكتور، على الأقل ما تبقى من قبسه.",
  "This is not like the M-12 mission.": "هذا ليس مثل مهمة M-12.",
  "This is not the end.": "ليست هذه هي النهاية.",
  "This is the depth where the M-12 went missing.": "هذا هو العمق الذي اختفت عنده السفينة M-12.",
  "This is your last warning.": "هذا تحذيرك الأخير.",
  "This line is restricted to authorized administrators only.": "هذا الخط مقتصر على المسؤولين المصرح لهم فقط.",
  "This mission is over.": "انتهت هذه المهمة.",
  "This mission was never about wisdom.": "لم تكن هذه المهمة يوماً عن الحكمة والتعقل.",
  "This recording will now be played back.": "سيتم تشغيل هذا التسجيل الآن.",
  "This unit allows for generation of a new dormitory <cf>access cassette.<cf><cf>- Insert THREE (3) VALID dorm cassettes into slots.<cf>- Press any key to begin synthesis.<cf>":
  "تتيح هذه الوحدة توليد كاسيت وصول <cf>جديد للمهاجع.<cf><cf>- أدخل ثلاثة (3) كاسيتات مهجع صالحة في الفتحات.<cf>- اضغط على أي مفتاح لبدء التركيب.<cf>",
  "Though I wonder why you are here, so far below the earth.": "مع أنني أتساءل لمَ أنت هنا، في هذه الأعماق السحيقة تحت الأرض.",
  "Though he still seemed intent on actually completing the mission.": "رغم أنه لا يزال يبدو مصمماً على إكمال المهمة فعلياً.",
  "To confirm payment, press 1. To cancel this request, press 2.": "لتأكيد الدفع اضغط 1، ولإلغاء هذا الطلب اضغط 2.",
  "To proceed, identify your rank.": "للمتابعة، حدد رتبتك.",
  "To proceed, we will ask you to confirm some details.": "للمتابعة، سنطلب منك تأكيد بعض التفاصيل.",
  "To remain still": "أن تلزم السكون والثبات",
  "Too much is riding on this mission. We should reserve extraction for a true emergency.": "الكثير معلق على هذه المهمة. يجب الاحتفاظ بطلب الإخلاء لحالات الطوارئ الحقيقية.",
  "Turn Around": "التفت للخلف",
  "Turn it to 100.7": "اضبطه على التردد 100.7",
  "Turn off the light": "أطفئ النور",
  "Type password, then hit enter": "اكتب كلمة المرور، ثم اضغط Enter",
  "Uncle Stepan came by.<cf>He is always kind and gives me candy sometimes.<cf>He doesn't have any hair.<cf>Dad says it's because Uncle Stepan has been underground for too long.":
  "زارنا العم ستيبان.<cf>إنه لطيف دائماً ويعطيني حلوى في بعض الأحيان.<cf>ليس لديه أي شعر في رأسه.<cf>يقول أبي إن ذلك بسبب بقاء العم ستيبان تحت الأرض لوقت طويل جداً.",
  "Uncle Stepan.": "العم ستيبان.",
  "Universal Remote": "جهاز تحكم شامل",
  "Unlabeled orange shell. The key to your own cell.": "غلاف برتقالي بلا تسمية. مفتاح زنزانتك الخاصة.",
  "Unlike me it doesn't want to help you.": "على عكسي، هو لا يريد مساعدتك.",
  "Upload the waypoint data.": "ارفع بيانات نقطة المسار.",
  "Used to receive orders. Not even 8 kilometers of stone can keep Strata from telling you what to do.": "يُستخدم لتلقي الأوامر. حتى 8 كيلومترات من الصخور الصلبة لا تمنع ستراتا من إملاء أوامرها عليك.",
  "Used to record and replay the precious few transmissions to reach these rumbling depths.": "يُستخدم لتسجيل وإعادة تشغيل الإرساليات النادرة القليلة التي تبلغ هذه الأعماق الهادرة.",
  "Used to relay lies and empty promises. This is all you will ever get from them.": "يُستخدم لنقل الأكاذيب والوعود الجوفاء. هذا كل ما ستناله منهم على الإطلاق.",
  "Verification is complete. All required details have been confirmed.": "اكتمل التحقق. تم تأكيد جميع التفاصيل المطلوبة.",
  "Viktor Kaminskyi": "فيكتور كامينسكي",
  "Viktor, it's Stepan.": "فيكتور، معك ستيبان.",
  "Viktor....": "فيكتور....",
  "Viktor?": "فيكتور؟",
  "Vostok Rental Notice<cf><cf>Mr. Kaminskyi.<cf>The rental period of your certified Vostok Recording Machine is coming to a close.<cf><cf>We understand that predicting a loved one's moment of passing can be difficult, which is why we are offering payment plans that are as fair as possible.<cf><cf>However, your bank is no longer willing to extend your credit defecit. If you are unable to deposit additional funds we will, regrettably, have to recall the recording equipment.<cf><cf><cf>":
  "إشعار تأجير فوستوك<cf><cf>السيد كامينسكي.<cf>فترة استئجار آلة تسجيل فوستوك المعتمدة الخاصة بك شارفت على الانتهاء.<cf><cf>نحن نتفهم أن التنبؤ بلحظة مفارقة شخص عزيز للحياة قد يكون أمراً عسيراً، ولهذا نقدم خطط سداد عادلة قدر الإمكان.<cf><cf>ومع ذلك، لم يعد مصرفك مستعداً لتمديد عجزك الائتماني. إذا لم تتمكن من إيداع مبالغ إضافية، فسنضطر بأسف لسحب واسترجاع معدات التسجيل.",
  "WARNING! <cf><cf>HIGH MAGMA CONCENTRATION DETECTED<cf>HULL CANNOT WITHSTAND TEMPERATURE<cf>OVER PROLONGED TIME<cf><cf>OVERRIDE EMERGENCY STOP WITH<cf>IGNITION KEY":
  "تحذير! <cf><cf>تم رصد تركيز عالٍ من الصهارة البركانية (الماجما)<cf>هيكل السفينة لا يستطيع تحمل الحرارة<cf>لفترة زمنية ممتدة<cf><cf>تجاوز التوقف الطارئ باستخدام<cf>مفتاح التشغيل",
  "WAYPOINT UP TO DATE": "نقطة المسار محدثة",
  "WAYPOINT: NOT SET": "نقطة المسار: غير محددة",
  "WHAT HELL WAS THAT?": "ما الجحيم الذي حدث للتو؟",
  "Wake up for the second time.": "استيقظ للمرة الثانية.",
  "Wake up.": "استيقظ.",
  "Wakes the MOLE. Every navigator's reminder of duty.": "يوقظ حفار إم.أو.إل.إي. تذكير لكل ملاّح بواجبه المقدس.",
  "Warning. Magma breach imminent. Relocate vessel immediately.": "تحذير. اختراق الصهارة وشيك. انقل السفينة فوراً.",
  "Wash away all these memories of funerals, and loss, and death.": "اغسل وامحُ كل هذه الذكريات عن الجنائز والفقد والموت.",
  "Waypoint Set.................YES": "تم تعيين نقطة المسار.................نعم",
  "We are on the brink of a discovery unlike anything mankind has ever seen.": "نحن على مشارف اكتشاف لا يشبه أي شيء شهدته البشرية من قبل.",
  "We are terminating your auto pilot systems in order to save power while we are discussing extraction.": "نقوم بإنهاء وإيقاف أنظمة الطيار الآلي لديكم لتوفير الطاقة ريثما نناقش عملية الإخلاء.",
  "We at Surface Control had our first moment of joy since the Matryoshka Incident when you completed the course correction.":
  "شعرنا في مركز التحكم السطحي بأول لحظة فرح منذ حادثة الماتريوشكا عندما أتممتم تصحيح المسار.",
  "We ate pancakes together.<cf>They were really good.<cf>Now I’m waiting to open my presents. I want a mole!":
  "تناولنا الفطائر معاً.<cf>كانت لذيذة جداً.<cf>والآن أنا أنتظر لفتح هداياي. أريد دمية خلد!",
  "We can't always save everyone we care about, Stepan.": "لا نستطيع دائماً إنقاذ كل من نهتم لأمرهم يا ستيبان.",
  "We did find what we were looking for all this time, you know.": "لقد وجدنا ما كنا نبحث عنه طوال هذا الوقت، كما تعلم.",
  "We discovered it after the Matryoshka incident.": "اكتشفناه بعد حادثة الماتريوشكا.",
  "We finally had an update from Stepan.": "تلقينا أخيراً مستجدات من ستيبان.",
  "We have taken to calling it the White Rabbit Signal.": "اعتدنا أن نطلق عليها اسم إشارة الأرنب الأبيض.",
  "We have the best house.<cf>My friends all think so too.<cf>Dad says that it's because he worked as a navigator.":
  "لدينا أفضل منزل على الإطلاق.<cf>أصدقائي يعتقدون ذلك أيضاً.<cf>يقول أبي إن ذلك بسبب عمله كملاّح.",
  "We haven't verified that.": "لم نتحقق من ذلك بعد.",
  "We thought they left us here to rot.": "ظننا أنهم تركونا هنا لنتعفن ونموت.",
  "We tried to lure him into Stepan's office with the gun as bait.": "حاولنا استدراجه إلى مكتب ستيبان مستخدمين المسدس كطُعم.",
  "We'll dig our way out of this hole together.": "سنحفر طريقنا للخروج من هذه الحفرة سوياً.",
  "We're so damn close.": "نحن قريبون جداً اللعنة.",
  "What I'm about to show you is the best recording we have.": "ما أوشك أن أريك إياه هو أفضل تسجيل نمتلكه.",
  "What is going on": "ما الذي يجري هنا؟",
  "What is going on?": "ما الذي يجري؟",
  "What the hell are you doing??": "ما الذي تفعله بحق الجحيم؟!",
  "When we extract we are going to need someone to take responsibility.": "عندما نقوم بالإخلاء سنحتاج إلى شخص يتحمل المسؤولية كاملة.",
  "When you're ready, just walk out the door.": "عندما تكون مستعداً، فقط اخرج من الباب.",
  "Where are you?": "أين أنت؟",
  "Where is everyone?": "أين الجميع؟",
  "Who keeps trying, until there is nothing left to try.": "من يواصل المحاولة، حتى لا يتبقى شيء آخر ليجربه.",
  "Wired raw reader circuit to screen. <cf>Place crystal on circuit to activate.": "تم توصيل دائرة القارئ الخام بالشاشة. <cf>ضع البلورة على الدائرة لتفعيلها.",
  "Wishful.": "تمنٍ ورجاء.",
  "With all due respect, I wonder if it is wise to play such a recording, if one exists.": "مع كامل الاحترام، أتساءل إن كان من الحكمة تشغيل تسجيل كهذا، إن كان موجوداً أصلاً.",
  "Would they care?": "وهل سيبالون؟",
  "Would you please turn on the lights?": "هل يمكنك تشغيل الأنوار لو سمحت؟",
  "Yes. Kaminskyi was just the most susceptible.": "نعم. كان كامينسكي هو الأكثر تأثراً وقابلية للتأذي فحسب.",
  "You already have a formal complaint in processing.": "لديك بالفعل شكوى رسمية قيد المعالجة.",
  "You are so close, Viktor.": "أنت قريب للغاية يا فيكتور.",
  "You can stay here as long as you like.": "يمكنك البقاء هنا للمدة التي ترغبها.",
  "You did well.": "لقد أحسنت صنعاً.",
  "You did.": "لقد فعلت ذلك.",
  "You don't have to do this.": "ليس عليك فعل هذا.",
  "You have reached Vostok Continuity Services.": "لقد اتصلت بخدمات استمرارية فوستوك.",
  "You have reached the Strata emergency service.": "لقد اتصلت بخدمة طوارئ ستراتا.",
  "You have to keep going, no matter what.": "عليك أن تواصل التقدم، مهما حدث.",
  "You have to make a choice, Viktor.": "عليك أن تختار يا فيكتور.",
  "You have to take it for yourself.": "عليك أن تأخذه بنفسك.",
  "You just have to find him again.": "عليك فقط العثور عليه مجدداً.",
  "You just have to get back into that cockpit.": "عليك فقط العودة إلى قمرة القيادة تلك.",
  "You just have to remember who stole him from you.": "عليك فقط أن تتذكر من الذي سرقه وانتزعه منك.",
  "You knew some of your selections were, shall we say, controversial.": "كنت تعلم أن بعض اختياراتك كانت، إن صح التعبير، مثيرة للجدل.",
  "You know how the situation is up here.": "أنت تعلم كيف هي الأوضاع هنا في الأعلى.",
  "You know what you are up against.": "أنت تدرك جيداً ما تواجهه.",
  "You made it through.": "لقد نجحت في العبور والنجاة.",
  "You must remember.": "عليك أن تتذكر.",
  "You must save him.": "يجب عليك أن تنقذه.",
  "You need to make some tough decisions.": "عليك اتخاذ بعض القرارات الصعبة والحاسمة.",
  "You never made it back to him in time.": "لم تتمكن أبداً من العودة إليه في الوقت المناسب.",
  "You opened your eyes to truly see.": "فتحت عينيك لتبصر الحقيقة بحق.",
  "You opened your eyes to truly see.<cf><cf><cf>Salvation is not something to be found through prayer or by chance.":
  "فتحت عينيك لتبصر الحقيقة بحق.<cf><cf><cf>الخلاص ليس شيئاً تعثر عليه بالدعاء أو بالمصادفة.",
  "You owe them nothing, Viktor.": "أنت لا تدين لهم بأي شيء يا فيكتور.",
  "You previously stated that the person's last confirmed happy memory occurred on their birthday.": "لقد ذكرت سابقاً أن آخر ذكرى سعيدة مؤكدة للشخص حدثت في عيد ميلاده.",
  "You recognize it, don't you?": "أنت تتعرف عليه، أليس كذلك؟",
  "You reveal to me revolutionary new discoveries. <cf><cf>How, while the frequency cannot be measured by conventional instruments, it can be interpreted using brain waves as a medium.<cf><cf>And how, while the frequency is chaotic and seemingly ever-changing, it can be stabilized and trapped with Hrytsenium.":
  "أنت تكشف لي عن اكتشافات ثورية جديدة. <cf><cf>كيف أنه، ورغم أن التردد لا يمكن قياسه بالأجهزة التقليدية، يمكن تفسيره باستخدام موجات الدماغ كوسيط ناقل.<cf><cf>وكيف أنه، رغم كون التردد فوضوياً ودائم التغير، يمكن تثبيته واحتجازه باستخدام الهريتسينيم.",
  "You seem good at that.": "يبدو أنك بارع في ذلك.",
  "You sit up there in that cockpit pretending you’re in control": "تجلس هناك بالأعلى في قمرة القيادة متظاهراً بأنك تسيطر على زمام الأمور",
  "You stubborn old idiot...": "أيها العجوز الأحمق العنيد...",
  "You were given a direct order to SIT TIGHT.": "لقد تلقيت أمراً مباشراً بأن تلزم مكانك ولا تتحرك.",
  "You were the one who put this crew together.": "أنت من جمع هذا الطاقم بنفسك.",
  "You'd think something that has caused so much havoc up here would be easier to find.": "كنت لتظن أن شيئاً تسبب بكل هذا الخراب هنا في الأعلى سيكون العثور عليه أسهل.",
  "You're part of Adamenko's crew, aren't you?": "أنت جزء من طاقم أدامينكو، أليس كذلك؟",
  "You're safe": "أنت في أمان",
  "You're safe<cf><cf>As long as you are in here I can hold it off<cf><cf>But you can't run from the past forever<cf><cf>If you are to overcome it, then you must face it head on":
  "أنت في أمان<cf><cf>طالما أنك هنا بالداخل يمكنني صده ومقاومته<cf><cf>لكنك لا تستطيع الهروب من الماضي للأبد<cf><cf>إن أردت التغلب عليه، فعليك مواجهته وجهاً لوجه",
  "You, if anyone, should know that sometimes a commander has to FACE REALITY, Stepan.": "أنت، أكثر من أي شخص آخر، يجب أن تعلم أن القائد عليه أحياناً أن يواجه الواقع المرير يا ستيبان.",
  "Your account is now in debt and may be subject to citizen review.": "حسابك الآن غارق في الديون وقد يخضع لمراجعة حالة المواطنة.",
  "Your orders for now: sit tight. Don't do anything stupid.": "أوامرك في الوقت الراهن: الزم مكانك ولا تفعل أي حماقة.",
  "Your son can still be saved.": "ابنك لا يزال من الممكن إنقاذه.",
  "Your son. All that matters. Save him, and he will save you.": "ابنك، هو كل ما يهم. أنقذه، وسينقذك بدوره.",
  "You’re poison, Viktor.": "أنت بمثابة السم الزعاف يا فيكتور.",
  "and awoke things that should have been left sleeping.": "وأيقظ أشياء كان ينبغي أن تترك نائمة في سباتها.",
  "and that it most likely isn't natural.": "وأنها في الغالب ليست ظاهرة طبيعية.",
  "by UNEASY": "تطوير UNEASY",
  "cassette inserted<cf>checking combability<cf>cassette read": "تم إدخال الكاسيت<cf>فحص التوافق<cf>تمت قراءة الكاسيت",
  "cassette inserted...<cf>checking combability...": "تم إدخال الكاسيت...<cf>جارٍ فحص التوافق...",
  "cassette inserted...<cf>checking combability...<cf>read and write permission granted<cf>reading();": "تم إدخال الكاسيت...<cf>فحص التوافق...<cf>تم منح إذن القراءة والكتابة<cf>قراءة();",
  "choose files to transfer": "اختر الملفات لنقلها",
  "digit four:<cf><cf>7": "الرقم الرابع:<cf><cf>7",
  "digit one:<cf><cf>8": "الرقم الأول:<cf><cf>8",
  "digit two:<cf><cf>3": "الرقم الثاني:<cf><cf>3",
  "digit three:<cf>5": "الرقم الثالث:<cf>5",
  "him.": "إياه.",
  "initiating...<cf>reading cassette...<cf>write permissions granted<cf>opening up register<cf>listing readable files":
  "جارٍ البدء...<cf>قراءة الكاسيت...<cf>تم منح أذونات الكتابة<cf>فتح السجل<cf>إدراج الملفات المقروءة",
  "loading system resources...": "تحميل موارد النظام...",
  "or let them devour you.": "أو دعهم يلتهمونك.",
  "parking check<cf><cf>central hospital 12<cf><cf>11.10.1980 08:54:27": "تذكرة موقف سيارات<cf><cf>المستشفى المركزي 12<cf><cf>11.10.1980 08:54:27",
  "proprietary software": "برمجيات مسجلة الملكية",
  "reading cassette<cf>saved data found<cf>start new found<cf>no further entries found": "قراءة الكاسيت<cf>تم العثور على بيانات محفوظة<cf>بدء إدخال جديد<cf>لا توجد مدخلات أخرى",
  "Recording...": "جارٍ التسجيل...",
  "seismic_decryptor.exe": "مفكك_التشفير_الزلزالي.exe",
  "version 1.4.5": "الإصدار 1.4.5",
  "waiting for readjustment...": "في انتظار إعادة الضبط...",
  "while the rest of us BURN IN FUCKING HELL DOWN HERE!": "بينما نحترق نحن البقية في جحيم لعين هنا بالأسفل!",
  "…Navigator.": "…أيها الملاّح.",
  "…Viktor.": "…فيكتور.",
  "Hello friend": "مرحباً يا صديقي",
  "I hate you": "أنا أكرهك",
  "Sil vous plait": "من فضلك",
  "Amélie Geeraert": "أميلي جيرارت",
  "Andreas Wangler": "أندرياس فانغلر",
  "Axel Olsson": "أكسيل أولسون",
  "Björn Riemann": "بيورن ريمان",
  "Bohdana Vozniuk": "بوهدانا فوزنيوك",
  "Breno Teles": "برينو تيليس",
  "Daniel Lyozov": "دانيال ليوزوف",
  "Fredrik Wisborg": "فريدريك ويسبورغ",
  "Jeremy Blaustein": "جيريمي بلاوستين",
  "Jochen Schütz": "يوخن شوتس",
  "Joe Dart": "جو دارت",
  "Jonas Ekholm": "جوناس إيكهولم",
  "Karl Bergman": "كارل بيرغمان",
  "Keira Larsson": "كيرا لارسون",
  "Kemel Cobresle": "كميل كوبريسل",
  "Veronica Johansson": "فيرونيكا يوهانسون"
};

// Main processing function
function processStrings() {
  const rawPath = path.join(__dirname, 'raw_strings.txt');
  const rawContent = fs.readFileSync(rawPath, 'utf8');
  const lines = rawContent.split(/\r?\n/);

  const entries = [];
  const translatedLines = [];

  for (let i = 0; i < lines.length; i++) {
    const orig = lines[i];
    const trimmed = orig.trim();
    let trans = orig;

    if (MASTER_DICT[orig]) {
      trans = MASTER_DICT[orig];
    } else if (MASTER_DICT[trimmed]) {
      trans = MASTER_DICT[trimmed];
    } else if (PHRASES[orig]) {
      trans = PHRASES[orig];
    } else if (PHRASES[trimmed]) {
      trans = PHRASES[trimmed];
    } else if (orig.includes('<cf>')) {
      const parts = orig.split('<cf>');
      const translatedParts = parts.map(p => {
        const pt = p.trim();
        return MASTER_DICT[p] || MASTER_DICT[pt] || PHRASES[p] || PHRASES[pt] || p;
      });
      trans = translatedParts.join('<cf>');
      // Also check credit headings inside
      trans = trans
        .replace(/- CONTRIBUTING PERSONNEL -/g, "- الموظفون المساهمون -")
        .replace(/- VOICE ACTING -/g, "- الأداء الصوتي -")
        .replace(/- Community Assistance/g, "- دعم ومساعدة المجتمع")
        .replace(/- Level Design/g, "- تصميم المراحل")
        .replace(/- Music Composing/g, "- التأليف الموسيقي")
        .replace(/- VFX Art/g, "- فن المؤثرات البصرية")
        .replace(/- UI & UX Design/g, "- تصميم واجهة وتجربة المستخدم")
        .replace(/- 2D Art and 3D Art/g, "- فن ثنائي وثلاثي الأبعاد")
        .replace(/- 2D Art and Game Design/g, "- الفنون وتصميم اللعبة")
        .replace(/- 2D Art/g, "- رسوم ثنائية الأبعاد")
        .replace(/- Head of Localization/g, "- رئيس قسم التعريب والترجمة")
        .replace(/- Project Manager/g, "- مدير المشروع")
        .replace(/- Test Coordinator/g, "- منسقة الاختبارات")
        .replace(/- Test Lead/g, "- قائد فريق الاختبار")
        .replace(/- Localization Support/g, "- دعم التعريب والترجمة")
        .replace(/- Founder & CEO/g, "- المؤسس والمدير التنفيذي")
        .replace(/- Chief Publishing Officer/g, "- رئيس قطاع النشر")
        .replace(/- Head of Communications/g, "- رئيس الاتصالات")
        .replace(/- Head of Business Development/g, "- رئيس تطوير الأعمال")
        .replace(/- Head of Scouting/g, "- رئيس الاستكشاف")
        .replace(/- Senior Producer/g, "- منتج أول");
    } else if (orig.includes('{/n}')) {
      const parts = orig.split('{/n}');
      const translatedParts = parts.map(p => {
        const pt = p.trim();
        return MASTER_DICT[p] || MASTER_DICT[pt] || PHRASES[p] || PHRASES[pt] || p;
      });
      trans = translatedParts.join('{/n}');
    }

    // Determine category
    let category = "system";
    if (orig.includes("Maria") || orig.includes("Stepan") || orig.includes("Viktor") || orig.includes("Petro") || orig.includes("Dad") || orig.includes("Letter") || orig.includes("Nov") || orig.includes("Nov 1982") || orig.includes("Nov<cf>1982")) {
      category = "story";
    } else if (orig.includes("PERSONNEL") || orig.includes("VOICE ACTING") || orig.includes("ORO INTERACTIVE") || orig.includes("CREW") || orig.includes("Localization")) {
      category = "credits";
    } else if (orig.includes("Option") || orig.includes("Back") || orig.includes("Confirm") || orig.includes("Left") || orig.includes("Right") || orig.includes("Crouch") || orig.includes("Sprint") || orig.includes("Interact") || orig.includes("Audio") || orig.includes("Graphics")) {
      category = "ui";
    } else if (orig.includes("RPM") || orig.includes("ENGINE") || orig.includes("TORPEDO") || orig.includes("FUSEBOX") || orig.includes("EXAM") || orig.includes("COCKPIT") || orig.includes("DRILL")) {
      category = "gameplay";
    }

    entries.push({
      id: i + 1,
      original: orig,
      translated: trans,
      isTranslated: trans !== orig,
      category
    });

    translatedLines.push(trans);
  }

  // Ensure directories exist
  const publicDir = path.join(__dirname, '..', 'public');
  const srcDataDir = path.join(__dirname, '..', 'src', 'data');
  if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
  if (!fs.existsSync(srcDataDir)) fs.mkdirSync(srcDataDir, { recursive: true });

  // Save public files
  fs.writeFileSync(path.join(publicDir, 'mole_game_original.txt'), rawContent, 'utf8');
  fs.writeFileSync(path.join(publicDir, 'mole_game_translated_ar.txt'), translatedLines.join('\n'), 'utf8');

  // Save JSON for React App
  fs.writeFileSync(path.join(srcDataDir, 'translations.json'), JSON.stringify(entries, null, 2), 'utf8');

  console.log(`Successfully processed ${entries.length} lines.`);
  console.log(`Translated lines count: ${entries.filter(e => e.isTranslated).length}`);
  console.log(`Files written to /public/ and /src/data/translations.json`);
}

processStrings();
