export const dictionaryPart2 = {
  // Letters & Transmission logs
  "08.11.1982<cf>Sender: Maria<cf><cf>I hate to say 'I told you so', Stepan. You were the one who put this crew together. You knew some of your selections were, shall we say, controversial.<cf><cf>And above all, you knew what risks those selections would bring.<cf><cf>Look, I'm not trying to be heartless. All I'm saying is that this is not one of those situations I can bail you out from. You need to make some tough decisions.<cf><cf>Too much is riding on this mission. We should reserve extraction for a true emergency.<cf>Sleeping troubles and the physical symptoms you are describing could very well be because you are several kilometers below the surface.<cf>It doesn't have to be the Signal.<cf><cf>Regardless, we at command are praying to all angels above that you will perservere. It sounds cliché, but the hope of the entire nation really does rest on your shoulders.":
  "08.11.1982<cf>المرسل: ماريا<cf><cf>أكره أن أقول \"لقد حذرتك يا ستيبان\". أنت من اختار هذا الطاقم بنفسك. كنت تعلم أن بعض اختياراتك كانت، إن صح التعبير، مثيرة للجدل.<cf><cf>وفوق كل شيء، كنت تدرك تماماً المخاطر التي قد تجلبها تلك الاختيارات.<cf><cf>اسمع، أنا لا أحاول أن أكون قاسية القلب. كل ما أقوله هو أن هذا ليس من تلك المواقف التي أستطيع إنقاذك منها. عليك أن تتخذ بعض القرارات الصعبة.<cf><cf>هناك الكثير معلق على نجاح هذه المهمة. ينبغي أن نحتفظ بطلب الإخلاء لحالات الطوارئ الحقيقية والقصوى فقط.<cf>اضطرابات النوم والأعراض الجسدية التي تصفها قد تكون ناتجة ببساطة عن وجودكم على عمق عدة كيلومترات تحت سطح الأرض.<cf>ليس بالضرورة أن تكون بسبب \"الإشارة\".<cf><cf>بصرف النظر عن ذلك، نحن في القيادة نصلي لجميع الملائكة في السماء لتثابروا وتصمدوا. قد يبدو الأمر تقليدياً ومبتذلاً، لكن أمل الأمة بأسرها يقع حقاً على عاتقك.",

  "08.11.1982 {/n}This is not me trying to say {/n}'I told you so', Stepan. {/n}{/n}I just want to remind you that{/n}this is your responsibility. {/n}{/n}In the end it's up to your judgement {/n}if the mission must be aborted. {/n}{/n}Your decision will of course be respected,{/n}but I think I speak for all of us {/n}when I say I hope{/n}you'll manage to keep going. {/n}{/n}Yours, always. {/n}Maria. Strata Mission Control. ":
  "08.11.1982 {/n}أنا لا أحاول أن أقول لك {/n}'لقد حذرتك'، يا ستيبان. {/n}{/n}أريد فقط تذكيرك بأن{/n}هذه مسؤوليتك وحدك. {/n}{/n}في النهاية، يعود الأمر لتقديرك {/n}فيما إذا كان يجب إلغاء المهمة. {/n}{/n}قرارك سيحظى بالطبع بكل الاحترام،{/n}لكنني أعتقد أنني أتحدث باسم الجميع {/n}عندما أقول إنني آمل أن{/n}تتمكنوا من مواصلة التقدم. {/n}{/n}المخلصة لك دائماً، {/n}ماريا. مركز التحكم بمهام ستراتا.",

  "08.11.1982 {/n}{/n}A new password for crew member 04 {/n}has been generated due to a system failure {/n}{/n}The new password is: 000715{/n}{/n}Ask the crew member for the reproduction steps {/n}and report the diagnostics to Strata mission control. ":
  "08.11.1982 {/n}{/n}تم إنشاء كلمة مرور جديدة لعضو الطاقم رقم 04 {/n}بسبب فشل في النظام {/n}{/n}كلمة المرور الجديدة هي: 000715{/n}{/n}اطلب من عضو الطاقم خطوات تكرار المشكلة {/n}وأبلغ عن بيانات التشخيص لمركز التحكم بمهام ستراتا.",

  "09.11.1982{/n}{/n}Stepan, we have not heard from you or the crew in 16 hours.{/n}{/n}In my mind the reason for your silence is either because something has happened{/n}and you are too stubborn to call the emergency number or you have reached a depth beyond what our communication lines can handle, in which case I want to remind you that you will be extracted automatically when you reach the target coordinates. I know there is a third option, but I refuse to accept that. {/n}{/n}Yours, always.{/n}Maria. Strata Mission Control.":
  "09.11.1982{/n}{/n}ستيبان، لم نسمع منك أو من الطاقم أي خبر منذ 16 ساعة.{/n}{/n}في تصوري، سبب صمتك إما أن أمراً جللاً قد وقع{/n}وأنت شديد العناد لدرجة الامتناع عن الاتصال برقم الطوارئ، أو أنكم بلغتم عمقاً يفوق قدرة خطوط اتصالاتنا على تحمله، وفي هذه الحالة أود تذكيرك بأنه سيتم سحبكم وإخلاؤكم تلقائياً فور وصولكم للإحداثيات المستهدفة. أعلم بوجود احتمال ثالث، لكني أرفض تصديقه.{/n}{/n}المخلصة لك دوماً،{/n}ماريا. مركز التحكم بمهام ستراتا.",

  "Dear Petro,<cf><cf>The day I'm writing this is you are just turning 6.<cf><cf>My plan is to give you this letter by the day you turn 16.<cf><cf>Or perhaps when you get your first job.<cf><cf>Or perhaps when you get married.<cf><cf>When does a child stop being a child?<cf><cf>I can tell you that when I look at you now, making noises with your toy-drill, or when you <cf>draw with all the colors that you have, or when you keep glancing out the window because, <cf>perhaps soon, the rain will be gone and we can go to the playground...<cf><cf>Right now I feel that you will always be my little boy. Forever.<cf><cf>I wonder what kind of young man you will be by the time I give this letter to you.<cf><cf>Will you be a rascal? Or a studious bookworm? Will you go to the Strata institute to be a <cf>Navigator like your dad? I hope not.<cf><cf>You'll probably be a bit ashamed of me, as teenagers usually are.<cf><cf>The only other thing I can say for certain is that no matter what path you choose in life,<cf>I will always love you.<cf><cf>Your father,<cf>Viktor<cf><cf>":
  "عزيزي بيترو،<cf><cf>في اليوم الذي أكتب فيه هذه الكلمات، تبلغ عامك السادس للتو.<cf><cf>خطتي هي أن أسلمك هذه الرسالة عندما تبلغ سن السادسة عشرة.<cf><cf>أو ربما عندما تبدأ وظيفتك الأولى.<cf><cf>أو لعله يوم زفافك.<cf><cf>متى يتوقف الطفل عن كونه طفلاً؟<cf><cf>أستطيع أن أقول لك إنني حين أنظر إليك الآن، وأنت تصدر أصواتاً بلعبة الحفار، أو حين <cf>ترسم بكل الألوان التي تملكها، أو حين تواصل التطلع من النافذة متأملاً <cf>أن ينجلي المطر قريباً لنذهب سوياً إلى الملعب...<cf><cf>في هذه اللحظة، أشعر أنك ستظل طفلي الصغير إلى الأبد.<cf><cf>أتساءل أي رجل ستكون حين تتسلم هذه الرسالة.<cf><cf>هل ستكون ولداً شقياً؟ أم باحثاً منكباً على كتبه؟ هل ستلتحق بمعهد ستراتا لتصبح <cf>ملاّحاً مثل والدك؟ آمل ألا تفعل.<cf><cf>ربما ستخجل مني قليلاً، كما يفعل المراهقون عادة.<cf><cf>الأمر الوحيد الآخر الذي أستطيع الجزم به هو أنه أياً كان الدرب الذي ستختاره في حياتك،<cf>سأظل أحبك دائماً وأبداً.<cf><cf>والدك،<cf>فيكتور",

  "2 nov<cf><cf>Fixed an issue with the engine filters. <cf>Right one breaks when under too much strain.<cf>Spoke to the pilot about it. Weird fucker.<cf><cf>4 nov<cf><cf>Right engine filter keeps breaking. Keeping an <cf>inventory on hand here in the shed for now.<cf>Guess Strata dug up the first junk they could find for this mission.<cf>Desperate times and all that. Idiots.<cf><cf>5 nov<cf><cf>Piece of shit filter broke again. Down to one spare now.<cf>It'll have to do.<cf>Keep having nightmares. Always about Liliya and Vira.<cf>Miss them so goddamn much.<cf><cf>7 nov<cf><cf>This mission was one big mistake from the start.<cf>Things go missing, everyone acts like lunatics, the pilot most of all.<cf>I bet my life he is risking this entire mission with that insane cassette of his.<cf>If Adamenko is too much of an idiot to steer this ship straight, then I'll do it myself.<cf>":
  "2 نوفمبر<cf><cf>أصلحت مشكلة في فلاتر المحرك. <cf>الفلتر الأيمن ينكسر عند التعرض لضغط مفرط.<cf>تحدثت مع الطيار بشأنه. شخص غريب الأطوار ملعون.<cf><cf>4 نوفمبر<cf><cf>فلتر المحرك الأيمن لا ينفك ينكسر. أحتفظ <cf>بمخزون إضافي هنا في الورشة حالياً.<cf>يبدو أن ستراتا نبشت أول خردة وجدتها لهذه المهمة.<cf>أوقات عصيبة وكل هذا الهراء. أغبياء.<cf><cf>5 نوفمبر<cf><cf>انكسر الفلتر اللعين مجدداً. لم يتبقَ سوى قطعة غيار واحدة.<cf>سيتعين علينا الاكتفاء بها.<cf>الكوابيس تلاحقني دون انقطاع. دائماً عن ليليا وفيرا.<cf>أفتقدهما بشدة تفوق الوصف.<cf><cf>7 نوفمبر<cf><cf>كانت هذه المهمة خطيئة كبرى منذ البداية.<cf>الأشياء تختفي، والجميع يتصرفون كمجانين، خاصة الطيار.<cf>أراهن بحياتي أنه يعرض المهمة برمتها للهلاك بكاسيته المجنون ذلك.<cf>إذا كان أدامينكو غبياً لدرجة تعجزه عن قيادة هذه السفينة باستقامة، فسأفعل ذلك بنفسي.<cf>",

  "FUSEBOX RESET PROTOCOL - REV. C": "بروتوكول إعادة ضبط صندوق المصاهر (الفيوزات) - المراجعة C",
  "FUSEBOX RESET PROTOCOL - REV.C<cf>Property of Orbis Systems. Unauthorized operation is punishable by law.<cf><cf>Step 1. Fuse Installation:<cf>Insert the fuses into the sockets. <cf>Do not force insertion, misalignment may cause shorting.<cf><cf>Step 2. Load Calibration:<cf>Rotate the middle selector knob to match the number of fuses installed.<cf><cf>Step 3. Circuit Activation:<cf>Press and hold the red glowing charge button until the indicator light turns solid green.<cf><cf>Step 4. Phase Alignment.<cf>Flip switches 1, 3, 6 and 7 into the upright (ON) position.<cf>Switches may be stiff, apply steady pressure.<cf><cf>Step 5: Main Breaker Engage:<cf>Pull down the breaker lever with a firm motion.":
  "بروتوكول إعادة ضبط صندوق المصاهر - المراجعة C<cf>ملكية لأنظمة أوربيس. التشغيل غير المصرح به يعاقب عليه القانون.<cf><cf>الخطوة 1. تركيب المصاهر:<cf>أدخل المصاهر في المقابس المخصصة. <cf>لا تستخدم القوة المفرطة، فقد يؤدي عدم المحاذاة إلى التماس كهربائي.<cf><cf>الخطوة 2. معايرة الحمل:<cf>أدر مقبض التحديد الأوسط ليطابق عدد المصاهر المثبتة.<cf><cf>الخطوة 3. تنشيط الدائرة:<cf>اضغط باستمرار على زر الشحن الأحمر المتوهج حتى يتحول ضوء المؤشر إلى اللون الأخضر الثابت.<cf><cf>الخطوة 4. محاذاة الطور:<cf>اقلب المفاتيح 1 و 3 و 6 و 7 إلى وضع التشغيل العمودي (ON).<cf>قد تكون المفاتيح صلبة، استخدم ضغطاً ثابتاً.<cf><cf>الخطوة 5: تعشيق القاطع الرئيسي:<cf>اسحب ذراع القاطع إلى الأسفل بحركة حازمة.",

  "STRATA COURSE CORRECTION EXAM<cf> 23 VI 1961<cf><cf>This examination constitutes the final assessment prior to Navigator certification.<cf>All responses are evaluated against Strata operational standards.<cf>Successful completion grants operational clearance.<cf><cf>Make us all proud, Viktor.<cf> Good luck.<cf><cf><cf><cf>1. According to the October Doctrine, what is the first step in a course <cf>correction procedure?<cf><cf>Activate the ping lever to strike the tunnel walls and gather raw seismic data<cf> <cf><cf>2. What must be done with raw echo data before it can be used?<cf><cf>Translate it into a visual terrain map through a decryptor<cf><cf><cf>3. After processing the echo data, how should the sonar arrows be adjusted?<cf><cf>The coordinate setter arrows should be pointed towards the least obstructed points on the screen.<cf>":
  "امتحان تعديل مسار ستراتا<cf> 23 يونيو 1961<cf><cf>يمثل هذا الاختبار التقييم النهائي قبل الحصول على رخصة الملاحة.<cf>يتم تقييم جميع الإجابات وفق معايير تشغيل ستراتا.<cf>الاجتياز بنجاح يمنح تصريح العمل الميداني.<cf><cf>اجعلنا فخورين بك يا فيكتور.<cf> بالتوفيق.<cf><cf><cf><cf>1. وفقاً لعقيدة أكتوبر، ما هي الخطوة الأولى في إجراء تصحيح المسار؟<cf><cf>تفعيل ذراع النبض الصوتي لضرب جدران النفق وجمع البيانات الزلزالية الخام<cf> <cf><cf>2. ما الذي يجب فعله ببيانات الصدى الخام قبل استخدامها؟<cf><cf>ترجمتها إلى خريطة تضاريس مرئية عبر جهاز فك التشفير<cf><cf><cf>3. بعد معالجة بيانات الصدى، كيف ينبغي ضبط أسهم السونار؟<cf><cf>يجب توجيه أسهم محدد الإحداثيات نحو النقاط الأقل انسداداً على الشاشة.<cf>",

  "4. After extracting coordinates from the sonar, how is the course correction carried out?<cf><cf>Input the coordinates into the pilot, then steer toward the target <cf>using the joystick<cf> <cf><cf>5. How is the correct throttle RPM determined for drilling?<cf><cf>Read the ground density from the decrypted data and match it <cf>to a RPM chart<cf><cf><cf>Score: ___ / 5<cf>Return completed exam to the front desk for evaluation.":
  "4. بعد استخراج الإحداثيات من السونار، كيف يتم تنفيذ تعديل المسار؟<cf><cf>إدخال الإحداثيات في نظام القيادة، ثم التوجيه نحو الهدف <cf>باستخدام عصا التحكم<cf> <cf><cf>5. كيف يتم تحديد معدل دورات الخانق (RPM) الصحيح لعملية الحفر؟<cf><cf>قراءة كثافة التربة من البيانات المشفرة ومطابقتها <cf>مع جدول معدلات الدوران<cf><cf><cf>الدرجة: ___ / 5<cf>أعد ورقة الامتحان المكتملة إلى مكتب الاستقبال للتقييم.",

  "Ground density chart<cf><cf>Ground density — Drill speed<cf><cf>2.20 g/cm³ → 70 rpm<cf>2.60 g/cm³ → 62 rpm<cf>3.00 g/cm³ → 54 rpm<cf>3.40 g/cm³ → 46 rpm<cf>3.70 g/cm³ → 38 rpm<cf>4.00 g/cm³ → 30 rpm<cf><cf>Exceeding max speed risks overheating or drill collapse.":
  "مخطط كثافة الأرض<cf><cf>كثافة الأرض — سرعة الحفار<cf><cf>2.20 جم/سم³ → 70 دورة/دقيقة<cf>2.60 جم/سم³ → 62 دورة/دقيقة<cf>3.00 جم/سم³ → 54 دورة/دقيقة<cf>3.40 جم/سم³ → 46 دورة/دقيقة<cf>3.70 جم/سم³ → 38 دورة/دقيقة<cf>4.00 جم/سم³ → 30 دورة/دقيقة<cf><cf>تجاوز السرعة القصوى يعرض الحفار لخطر السخونة المفرطة أو الانهيار.",

  "A Remarkable Revival!<cf><cf>Just when you thought old man Kaminskyi had lost his touch he does it again. Taras Kaminskyi, who became a household name when he cemented the record for deepest descent in 1964, describes himself as someone who has always been a restless soul.<cf>\"Back in the heydays of drilling they just couldn't keep me away from the ground,\" Kaminskyi says. \"The people at Strata used to say I must be part Mole.\"<cf><cf>It's been nine years since Strata's last manned deep-earth drilling mission. Destabilized bedrock and falling mineral prices has been some of the reasons why vessels such as the M-12 were figuratively put on the shelf.<cf>\"It felt right, somehow,\" Kaminskyi laughs when asked about why he choose to accept a mission that is as daring as it is dangerous. \"The M-12 and I have been through a lot together. When Strata unveiled the mission I just thought to myself, 'no way I'm letting anyone else go down with her.'\"":
  "عودة مذهلة!<cf><cf>في الوقت الذي ظن فيه الجميع أن العجوز كامينسكي قد فقد براعته، يفعلها مجدداً. تاراس كامينسكي، الذي بات اسمه يتردد في كل بيت عندما حطم الرقم القياسي لأعمق هبوط عام 1964، يصف نفسه بأنه روح لا تهدأ أبداً.<cf>يقول كامينسكي: \"في أوج عصر الحفر الذهبي، لم يكونوا قادرين على إبعادي عن باطن الأرض. اعتاد العاملون في ستراتا القول إنني لا بد وأن أكون نصف خلد.\"<cf><cf>مرت تسع سنوات منذ آخر مهمة حفر مأهولة لأعماق الأرض نظمتها ستراتا. كانت الصخور غير المستقرة وهبوط أسعار المعادن من بين أسباب وضع سفن مثل M-12 على الرف مجازياً.<cf>يضحك كامينسكي عند سؤاله عن سبب قبوله مهمة تتسم بالجرأة والخطر البالغ: \"شعرت بطريقة ما أن هذا هو الصواب. لقد خضت أنا والسفينة M-12 الكثير معاً. وعندما كشفت ستراتا عن المهمة، قلت لنفسي على الفور: 'مستحيل أن أدع أي شخص آخر يهبط بها'.\""
};
